/**-- PROCEDIMENTO 
  1. TABELA TEMPORÁRIA COM OS REGISTROS A SEREM INCLUIDOS
  1.1. SOMENTE ESTATUTARIOS ATIVOS COM ALGUM CARGO EFETIVO OU COMISSIONADO VIGENTE
  1.2. NÃO GEROU PARA SERVIDORES SUSTADO COM AFASTAMENTO NÃO REMUNERADO NO PERÍODO


**/


INSERT INTO EMOVPERIODOAQUISITIVOFERIAS
(
          CDPERIODOAQUISITIVOFERIAS,
          CDVINCULO,
          DTINICIO,
          DTFIMPREVISTO,
          DTFIM,
          
          NUDIASFERIASPERDIDO,
          NUDIASFERIASABONADO,
          
           CDSITUACAOPERIODOAQFERIAS,
          
           NUDIASFERIASCONCEDIDO,
          
          FLAJUSTEDPRO,
          
          NUCPFCADASTRADOR,
          DTINCLUSAO,
          DTULTALTERACAO
) SELECT * FROM ETMP_SOL_14317_2022 T
   WHERE -- CDVINCULO = 2868 AND
   NOT EXISTS (SELECT 1 FROM EMOVPERIODOAQUISITIVOFERIAS PA WHERE PA.CDVINCULO = T.CDVINCULO AND PA.DTINICIO=T.DTINICIO);
   
   -- EXCLUIR 
      DELETE EMOVPERIODOAQUISITIVOFERIAS PA
        WHERE PA.CDPERIODOAQUISITIVOFERIAS IN (SELECT CDPERIODOAQUISITIVOFERIAS FROM ETMP_SOL_14317_2022);
        
-- ALGUM PA PREVISTO?
   SELECT *  FROM EMOVPERIODOAQUISITIVOFERIAS WHERE CDSITUACAOPERIODOAQFERIAS=1;
   SELECT * FROM ETMP_SOL_14317_2022 T        WHERE CDSITUACAOPERIODOAQFERIAS=1;
   
CREATE TABLE ETMP_SOL_14317_2022 AS 

-- 2015 -- 2022
WITH ANOS AS (
SELECT 2015 + LEVEL - 1 AS ANO FROM DUAL CONNECT BY LEVEL <= 8
) -- SELECT * FROM ANOS;
,
TAB_PA AS
(
SELECT
   
   V.CDVINCULO
  ,ADD_MONTHS(V.DTADMISSAO, 12 * (A.ANO - EXTRACT(YEAR FROM V.DTADMISSAO)))            AS DTINICIO
  ,ADD_MONTHS(V.DTADMISSAO, 12 * ((A.ANO - EXTRACT(YEAR FROM V.DTADMISSAO)) + 1)) - 1  AS DTFIMPREVISTO
  ,ADD_MONTHS(V.DTADMISSAO, 12 * ((A.ANO - EXTRACT(YEAR FROM V.DTADMISSAO)) + 1)) - 1  AS DTFIM
  ,0 AS NUDIASFERIASPERDIDO
  ,0 AS NUDIASFERIASABONADO
  ,NULL AS CDAFASTAMENTO
  ,'11111111111'   AS NUCPFCADASTRADOR
  ,TRUNC(SYSDATE)  AS DTINCLUSAO
  ,SYSTIMESTAMP    AS DTULTALTERACAO

,NULL AS DTFIMANTESPERDA
,CASE WHEN 1=1
     THEN 2 -- CONQUISTADO 
     ELSE 1 -- PREVISTO
 END  AS CDSITUACAOPERIODOAQFERIAS
,NULL AS DTINICIOULTPAAPROVEITADO
,NULL AS DTFIMULTPAAPROVEITADO
,NULL AS NUDIASUSUFRUIRAPROVEITADO
,NULL AS DEOBSULTPAAPROVEITADO
,30   AS NUDIASFERIASCONCEDIDO
,'N'  AS FLAJUSTEDPRO
,NULL AS VLSALDOINDFERIASVENCIDAS
,NULL AS VLSALDOINDFERIASPROP
,NULL AS INTIPOCALCULOSALDO
,NULL AS NUANOMESINICIOPAGRESCISAO
,NULL AS NUPERIODOSAPURADOS
,NULL AS NUMESESAPURADOS
,NULL AS FLINDENIZACAOHOMOLOGADA
-- PARA VERIFICAÇÃO
,PKGUTIL.FFORMATAMATRICULA(V.NUMATRICULA, V.NUDVMATRICULA, V.NUSEQMATRICULA) MATRICULA 

FROM ECADVINCULO V
JOIN ANOS A ON A.ANO > EXTRACT(YEAR FROM DTADMISSAO) AND A.ANO <= 2021

WHERE A.ANO NOT IN (SELECT EXTRACT(YEAR FROM AQ.DTINICIO) 
                     FROM EMOVPERIODOAQUISITIVOFERIAS AQ 
                     WHERE AQ.CDVINCULO = V.CDVINCULO
                   )
  AND DTDESLIGAMENTO IS NULL
  AND V.CDREGIMETRABALHO = 2 -- ESTATUATIO
  AND V.CDSITUACAOPREVIDENCIARIA = 1
  -- AND V.NUMATRICULA IN (0940231, 0939654, 0956093)
  --AND V.CDORGAO = 44
    --  AND V.NUMATRICULA IN (3109)
  
  
  AND 
  (  EXISTS (SELECT 1 FROM ECADHISTCARGOEFETIVO EF 
              WHERE    EF.CDVINCULO = V.CDVINCULO  
                   AND EF.FLANULADO = 'N'
                   AND EF.FLPRINCIPAL = 'S'
                   AND EF.CDREGIMETRABALHO  = 2
                   AND EF.DTINICIO <= SYSDATE 
                   AND (EF.DTFIM   >= SYSDATE OR DTFIM IS NULL)       )
          OR 
          
    EXISTS (SELECT 1 FROM ECADHISTCARGOCOM CCO 
                  WHERE    CCO.CDVINCULO = V.CDVINCULO  
                       AND CCO.FLANULADO = 'N'
                       AND CCO.FLPRINCIPAL = 'S'
                       AND CCO.CDREGIMETRABALHO  = 2
                       AND CCO.DTINICIO <= SYSDATE 
                       AND (CCO.DTFIM   >= SYSDATE OR DTFIM IS NULL)       )
   )  
   
 
   
ORDER BY 1, 2
)
-- , TAB_FINAL AS (
   SELECT 
          SMOVPERIODOAQUISITIVOFERIAS.NEXTVAL AS CDPERIODOAQUISITIVOFERIAS,
          CDVINCULO,
          DTINICIO,
          DTFIMPREVISTO,
          DTFIM,
          
          NUDIASFERIASPERDIDO,
          NUDIASFERIASABONADO,
          
          CASE WHEN TO_CHAR(DTFIM, 'YYYYMM') <= 202204 
            THEN 2 -- CONQUISTADO
            ELSE 1 -- PREVISTO
          END AS CDSITUACAOPERIODOAQFERIAS,
          
          CASE WHEN TO_CHAR(DTFIM, 'YYYYMM') <= 202204 
            THEN 30 -- CONQUISTADO
            ELSE 0 -- PREVISTO
          END AS NUDIASFERIASCONCEDIDO,
          
          FLAJUSTEDPRO,
          
          NUCPFCADASTRADOR,
          DTINCLUSAO,
          DTULTALTERACAO
          
         -- ,MATRICULA
   FROM TAB_PA T
    WHERE 
        NOT 
         EXISTS (SELECT 1 
                    FROM EAFAAFASTAMENTOVINCULO A
                     WHERE A.CDVINCULO = T.CDVINCULO 
                           AND A.FLANULADO = 'N'
                           AND A.DTINICIO <= T.DTINICIO
                           AND (A.DTFIM   >= T.DTFIM  OR  A.DTFIM IS NULL)
                           AND A.FLREMUNERADO = 'N' -- SUSTADO OU OUTROS
                           --AND A.CDMOTIVOAFASTTEMPORARIO != 6528
                         )
    ; -- FIM
    
    -- VERIFICAÇÕES
    

   -- 619 COM AFASTAMENTO 
   -- SELECT COUNT(DISTINCT CDVINCULO) FROM TAB_FINAL;
   --SELECT COUNT(DISTINCT MATRICULA) FROM TAB_FINAL;
    -- SELECT DISTINCT MATRICULA FROM TAB_FINAL
  --  SELECT * FROM TAB_FINAL WHERE MATRICULA LIKE '0943306-6-01'
   
   ;
   
   
 SELECT DISTINCT CDVINCULO 
  FROM EMOVPERIODOAQUISITIVOFERIAS
 WHERE CDVINCULO = 36589;
    
 
 SELECT * FROM EAFAHISTMOTIVOAFASTTEMP T WHERE T.DEMOTIVOAFASTTEMPORARIO LIKE 'SUSTADO';

SELECT CDVINCULO FROM ECADVINCULO V WHERE NUMATRICULA LIKE 0004348 AND NUSEQMATRICULA = 1; 
