SIGRH-TRE:
    dialect: 'oracle'
    sql_driver: 'cx_oracle'
    dsn_tns:
      host: 192.168.10.242
      service: bdteste.financas.pref
      port: 1521
    user: sigrhtre
    password: tr3Mcz

SIGRH-PRD:
    dialect: 'oracle'
    sql_driver: 'cx_oracle'
    dsn_tns:
      host: 192.168.10.247
      service: sigrhprod.financas.pref
      port: 1521
    user: sigrhprd
    password: prdM4c3i0

SQLite-Test:
    dialect: 'sqlite'
    dbworkpath: 'SQLite'
    dbfilename: 'database'
    dbext: 'sqlite'
