SELECT O.SGORGAO,
       V.NUMATRICULA || '-' || V.NUDVMATRICULA || '-' ||
       LPAD(V.NUSEQMATRICULA, 2, '0'),
       P.NMPESSOA,
       B.NUBANCO,
       A.NUAGENCIA,
       D.NUCONTACREDITO
  FROM ECADVINCULO V
 INNER JOIN ECADHISTDADOSBANCARIOSVINCULO D
    ON V.CDVINCULO = D.CDVINCULO
 INNER JOIN ECADPESSOA P
    ON P.CDPESSOA = V.CDPESSOA
 INNER JOIN VCADORGAO O
    ON O.CDORGAO = V.CDORGAO
 INNER JOIN ECADAGENCIA A
    ON A.CDAGENCIA = D.CDAGENCIACREDITO
 INNER JOIN ECADBANCO B
    ON B.CDBANCO = A.CDBANCO
 WHERE (DTDESLIGAMENTO IS NULL OR DTDESLIGAMENTO > SYSDATE)
   AND D.DTFIMVIGENCIA IS NULL
   AND LPAD(NUCONTACREDITO, 12, '0') = '000000000000'