insert all
into ecadunidadeorganizacional values (
 cdunidadeorganizacional,
 cdorgao,
 dtultalteracao,
 fluoativa,
 demotivosituacao,
 flpertenceorganograma
)

into ecadhistunidadeorganizacional values (
 cdhistunidadeorganizacional,
 cdorgao,
 cdunidadeorganizacional,
 dtiniciovigencia,
 dtfimvigencia,
 sgunidadeorganizacional,
 nmunidadeorganizacional,
 deemail,
 delei,
 cdsubtipounidorg,
 nucnpj,
 cdendereco,
 nuddd,
 nutelefone,
 nuramal,
 nudddfax,
 nufax,
 nuramalfax,
 cdtipocargahoraria,
 nucargahoraria,
 flcontracheque,
 flstaff,
 flsdr,
 cdestruturacarreira,
 cdfuncaochefia,
 cdcargocomissionado,
 cdpessoaautoridade,
 cduoautoridade,
 nucpfcadastrador,
 dtinclusao,
 flgestorapensao,
 flmunicipalizada,
 nuconveniomunic,
 flatividadepolicial,
 dtultalteracao,
 cdregiao,
 cduosupadm,
 cduosuprh,
 cduosuptecnica,
 cduosuphierarq,
 cduosupescala,
 flultimafinalizacao,
 cdlotacaosirh,
 cdtipounidorg,
 cdregiaoagrup,
 flfilial,
 cdcentrocusto,
 cdestruturacarreiratit,
 nunivelpagamento,
 nureferenciapagamento,
 flimprimirfolhafreq,
 cdcompradoraorgao,
 cdresponsavelgfip,
 nucnae,
 nualiquotarat,
 nucodigofpas,
 nucodigooutrasentidades,
 nucodigopagamentogps,
 vlpercentualinsspatronal,
 vlaliquotafap,
 vlaliquotaterceiros,
 fltiporespgfip,
 fluoinativo,
 delotacaosirh,
 denuprocessoja,
 incontratojovemaprendiz,
 intipocontroleponto,
 cdresponsaveljovemaprendiz,
 nucnpjentidadeja,
 fltipocontratoja,
 nucnpjsindicato,
 deemailsalternativos,
 flpadraoinclusaohistorico,
 flutilizalpdigital
)

select
(select nvl(max(cdhistunidadeorganizacional),0) from ecadhistunidadeorganizacional) + rownum as cdhistunidadeorganizacional,
'35' as cdorgao,
(select nvl(max(cdunidadeorganizacional),0) from ecadunidadeorganizacional) + rownum as cdunidadeorganizacional,
to_date('01/01/1980','DD/MM/RRRR') as dtiniciovigencia,
null as dtfimvigencia,
siglaunidadeorganizacional as sgunidadeorganizacional,
siglaunidadeorganizacional as nmunidadeorganizacional,
null as deemail,
null as delei,
null as cdsubtipounidorg,
null as nucnpj,
null as cdendereco,
null as nuddd,
null as nutelefone,
null as nuramal,
null as nudddfax,
null as nufax,
null as nuramalfax,
'1' as cdtipocargahoraria,
'8' as nucargahoraria,
'N' as flcontracheque,
'N' as flstaff,
'N' as flsdr,
null as cdestruturacarreira,
null as cdfuncaochefia,
null as cdcargocomissionado,
null as cdpessoaautoridade,
null as cduoautoridade,
'11111111111' as nucpfcadastrador,
trunc(sysdate) as dtinclusao,
'N' as flgestorapensao,
'N' as flmunicipalizada,
null as nuconveniomunic,
'N' as flatividadepolicial,
systimestamp as dtultalteracao,
null as cdregiao,
null as cduosupadm,
null as cduosuprh,
null as cduosuptecnica,
null as cduosuphierarq,
null as cduosupescala,
'N' as flultimafinalizacao,
null as cdlotacaosirh,
null as cdtipounidorg,
null as cdregiaoagrup,
'N' as flfilial,
null as cdcentrocusto,
null as cdestruturacarreiratit,
null as nunivelpagamento,
null as nureferenciapagamento,
'S' as flimprimirfolhafreq,
null as cdcompradoraorgao,
null as cdresponsavelgfip,
null as nucnae,
null as nualiquotarat,
null as nucodigofpas,
null as nucodigooutrasentidades,
null as nucodigopagamentogps,
null as vlpercentualinsspatronal,
null as vlaliquotafap,
null as vlaliquotaterceiros,
null as fltiporespgfip,
'N' as fluoinativo,
null as delotacaosirh,
null as denuprocessoja,
null as incontratojovemaprendiz,
null as intipocontroleponto,
null as cdresponsaveljovemaprendiz,
null as nucnpjentidadeja,
null as fltipocontratoja,
null as nucnpjsindicato,
null as deemailsalternativos,
'N' as flpadraoinclusaohistorico,
'S' as flutilizalpdigital,

'S' as fluoativa,
null as demotivosituacao,
'S' as flpertenceorganograma

from (
select distinct trim(t.siglaunidadeorganizacional) as siglaunidadeorganizacional
from SIGRHMIG.EMIGVINCULOEFETIVO t
left join vcadorgao o on trim(replace(o.sgorgao,'-','')) = trim(replace(t.sgorgao,'-',''))
where o.cdorgao is null
union
select distinct trim(t.siglaunidadeorganizacional) as siglaunidadeorganizacional
from SIGRHMIG.EMIGVINCULOCOMISSIONADO t
left join vcadorgao o on trim(replace(o.sgorgao,'-','')) = trim(replace(t.sgorgao,'-',''))
where o.cdorgao is null
)