-- Selecionando informa��es de bairro e munic�pio
SELECT B.*
FROM ECADBAIRRO B
INNER JOIN ECADLOCALIDADE L
  ON L.CDLOCALIDADE = B.CDLOCALIDADE
WHERE L.SGESTADO = 'AL'
 AND L.CDLOCALIDADE = 101;

SELECT * FROM CEP_LOCALIDADE A WHERE A.LOC_NU = 109;

select * from ECADLOCALIDADE L
 where L.SGESTADO = 'AL'
   and L.CDLOCALIDADE = 101;

select * from ECADBAIRRO B
 where B.CDLOCALIDADE = 101;