
  with exemplo as 
 (
    select
      lpad(v.numatricula, 7, 0)||'-'||v.nudvmatricula||'-'||lpad(v.nuseqmatricula, 2, 0) as Matricula,
      pe.nmpessoa                                                                        as Nome,
      pe.nucpf                                                                           as CPF,
      banco.nubanco                                                                      as NuBanco,
      ag.nuagencia                                                                       as NuAgencia,
      db.nucontacredito||'-'||db.nudvcontacredito                                        as Conta,
      case when ent.nmcargo is not null then ent.nmcargo else ent.nmcargoapoio end       as Cargo,
      case when ent.nmfuncaochefia is not null then ent.nmfuncaochefia 
           when ent.nmcargocomissionado is not null then ent.nmcargocomissionado
             else ent.nmfuncaoapoio end                                                  as Funcao_Comissionado,
      ent.situacao                                                                       as Situacao,
      v.dtadmissao                                                                       as Admissao,
      ent.dtadmissao2                                                                    as Admissao2,
      ent.instrucao                                                                      as Instrucao,
      o.nmorgao                                                                          as Secretaria,
      cc.nmcentrocusto                                                                   as Centro_de_Custo,
      case when ent.situacao = 'INATIVO' then ent.codnivapo else ent.nunivelcef||'-'||ent.nureferenciacef end as CodNiv,
      case when nvl(ent.nucho, 0) > 0 then ent.nucho else ent.nuchoapoio end             as Carga, 
      ent.sgtipocredito                                                                  as RegimePrev,
      
      ent.nurubrica                                                                      as Rubrica,      
      sum(ent.valor)                                                                     as Total
     
      from CONSOLIDADO_IPREV ent  
      
        inner join ecadvinculo v on v.cdvinculo =  ent.vinculo
        inner join ecadpessoa pe on pe.cdpessoa = v.cdpessoa
        inner join vcadorgao o on o.cdorgao = v.cdorgao
        inner join ecadhistdadosbancariosvinculo db on db.cdvinculo = v.cdvinculo and db.dtfimvigencia is null
        inner join ecadagencia ag on ag.cdagencia = db.cdagenciacredito 
        inner join ecadbanco banco on banco.cdbanco = ag.cdbanco    
        inner join ecadcentrocusto cc on cc.cdcentrocusto = ent.centrodecusto
      
        group by lpad(v.numatricula, 7, 0)||'-'||v.nudvmatricula||'-'||lpad(v.nuseqmatricula, 2, 0), 
                 pe.nmpessoa, 
                 pe.nucpf,
                 banco.nubanco,
                 ag.nuagencia,
                 db.nucontacredito||'-'||db.nudvcontacredito,
                 case when ent.nmcargo is not null then ent.nmcargo else ent.nmcargoapoio end,
                 case when ent.nmfuncaochefia is not null then ent.nmfuncaochefia 
                      when ent.nmcargocomissionado is not null then ent.nmcargocomissionado
                       else ent.nmfuncaoapoio end,
                 ent.situacao,
                 v.dtadmissao,
                 ent.dtadmissao2,
                 ent.instrucao,
                 o.nmorgao,
                 cc.nmcentrocusto,
                 case when ent.situacao = 'INATIVO' then ent.codnivapo else ent.nunivelcef||'-'||ent.nureferenciacef end,
                 case when nvl(ent.nucho, 0) > 0 then ent.nucho else ent.nuchoapoio end,
                 ent.sgtipocredito,
                 ent.nurubrica   
 
        order by lpad(v.numatricula, 7, 0)||'-'||v.nudvmatricula||'-'||lpad(v.nuseqmatricula, 2, 0), 
                 pe.nmpessoa, 
                 pe.nucpf,
                 banco.nubanco,
                 ag.nuagencia,
                 db.nucontacredito||'-'||db.nudvcontacredito,
                 case when ent.nmcargo is not null then ent.nmcargo else ent.nmcargoapoio end,
                 case when ent.nmfuncaochefia is not null then ent.nmfuncaochefia 
                      when ent.nmcargocomissionado is not null then ent.nmcargocomissionado
                       else ent.nmfuncaoapoio end,
                 ent.situacao,
                 v.dtadmissao,
                 ent.dtadmissao2,
                 ent.instrucao,
                 o.nmorgao,
                 cc.nmcentrocusto,
                 case when ent.situacao = 'INATIVO' then ent.codnivapo else ent.nunivelcef||'-'||ent.nureferenciacef end,
                 case when nvl(ent.nucho, 0) > 0 then ent.nucho else ent.nuchoapoio end,
                 ent.sgtipocredito,
                 ent.nurubrica   
  
 )
     
     select * from exemplo
     pivot (SUM(Total) 
               for Rubrica IN  ( 
                                1,
                                2,
                                3,
                                4,
                                5,
                                7,
                                8,
                                10,
                                11,
                                12,
                                13,
                                14,
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                44,
                                45,
                                58,
                                100,
                                101,
                                103,
                                108,
                                115,
                                118,
                                119,
                                120,
                                121,
                                122,
                                126,
                                129,
                                130,
                                131,
                                132,
                                133,
                                140,
                                141,
                                142,
                                148,
                                149,
                                157,
                                158,
                                161,
                                165,
                                171,
                                173,
                                174,
                                176,
                                177,
                                178,
                                179,
                                182,
                                183,
                                190,
                                192,
                                195,
                                199,
                                200,
                                201,
                                213,
                                214,
                                215,
                                216,
                                217,
                                218,
                                219,
                                220,
                                221,
                                222,
                                231,
                                235,
                                237,
                                239,
                                242,
                                244,
                                250,
                                252,
                                260,
                                265,
                                266,
                                267,
                                270,
                                275,
                                276,
                                281,
                                296,
                                298,
                                300,
                                301,
                                302,
                                304,
                                305,
                                306,
                                308,
                                310,
                                312,
                                314,
                                315,
                                316,
                                317,
                                318,
                                319,
                                320,
                                324,
                                325,
                                327,
                                328,
                                330,
                                337,
                                339,
                                341,
                                346,
                                347,
                                348,
                                349,
                                350,
                                351,
                                357,
                                365,
                                373,
                                377,
                                386,
                                387,
                                388,
                                389,
                                392,
                                394,
                                395,
                                396,
                                397,
                                399,
                                400,
                                404,
                                406,
                                407,
                                409,
                                411,
                                412,
                                413,
                                414,
                                415,
                                418,
                                419,
                                426,
                                428,
                                429,
                                430,
                                499,
                                502,
                                503,
                                505,
                                510,
                                511,
                                512,
                                513,
                                514,
                                515,
                                588,
                                589,
                                590,
                                597,
                                598,
                                599,
                                679,
                                681,
                                682,
                                684,
                                686,
                                687,
                                689,
                                690,
                                691,
                                693,
                                696,
                                698,
                                699)          
           )
             
