select * from openjson ('[
{"de":"CASACIVIL",  "para":"CASA CIVIL"},
{"de":"CERIM",      "para":"CASA CIVIL"},
{"de":"CSAMILITAR", "para":"CASA MILITAR"},
{"de":"BM",         "para":"CBM-RR"},
{"de":"COGERR",     "para":"COGER"},
{"de":"DEFPUB",     "para":"DPE-RR"},
{"de":"IDEFER",     "para":"IDEFER-RR"},
{"de":"IPEM",       "para":"IPEM-RR"},
{"de":"CONJUCERR",  "para":"JUCERR"},
{"de":"OGERR",      "para":"OGE-RR"},
{"de":"POLCIVIL",   "para":"PC-RR"},
{"de":"PROGE",      "para":"PGE-RR"},
{"de":"PM",         "para":"PM-RR"},
{"de":"CONCULT",    "para":"SECULT"},
{"de":"CONEDUC",    "para":"SEED"},
{"de":"PRODEB",     "para":"SEED"},
{"de":"CONREFIS",   "para":"SEFAZ"},
{"de":"PENSIONIST", "para":"SEGAD"},
{"de":"CONRODE",    "para":"SEINF"},
{"de":"CONANTD",    "para":"SEJUC"},
{"de":"CONPEN",     "para":"SEJUC"},
{"de":"SEEPE",      "para":"SEPE"},
{"de":"PLANTONIST", "para":"SESAU"},
{"de":"SEURB",      "para":"SEURB-RR"},
{"de":"UNIVIR",     "para":"UNIVIRR"},
{"de":"VICE GOV",   "para":"VICE-GOV"}
]') with (de varchar(20) '$.de', para varchar(20) '$.para')
