SELECT V.NUMATRICULA,P.NMPESSOA, A.DTINICIO, A.DTFIM, H.DEMOTIVOAFASTDEFINITIVO 
FROM EAFAAFASTAMENTOVINCULO A
INNER JOIN EAFAMOTIVOAFASTDEFINITIVO D
ON A.CDMOTIVOAFASTDEFINITIVO = D.CDMOTIVOAFASTDEFINITIVO
INNER JOIN EAFAHISTMOTIVOAFASTDEF H
ON H.CDMOTIVOAFASTDEFINITIVO = D.CDMOTIVOAFASTDEFINITIVO
INNER JOIN ECADVINCULO V
  ON V.CDVINCULO = A.CDVINCULO
INNER JOIN ECADPESSOA P
  ON P.CDPESSOA = V.CDPESSOA  

UNION

SELECT V.NUMATRICULA,P.NMPESSOA, A.DTINICIO, A.DTFIM, H.DEMOTIVOAFASTTEMPORARIO 
FROM EAFAAFASTAMENTOVINCULO A
INNER JOIN EAFAMOTIVOAFASTTEMPORARIO T
ON A.CDMOTIVOAFASTTEMPORARIO = T.CDMOTIVOAFASTTEMPORARIO
INNER JOIN EAFAHISTMOTIVOAFASTTEMP H
ON H.CDMOTIVOAFASTTEMPORARIO = T.CDMOTIVOAFASTTEMPORARIO
INNER JOIN ECADVINCULO V
  ON V.CDVINCULO = A.CDVINCULO
INNER JOIN ECADPESSOA P
  ON P.CDPESSOA = V.CDPESSOA  
