select 'ADM' as Modulo, 'DIASEMANA' as Dominio, TO_CHAR(CDDIASEMANA) as Codigo, TO_CHAR(DEDIASEMANA) as Descricao
from EADMDIASEMANA

union

select 'ADM' as Modulo, 'OPCAODIARIO' as Dominio, TO_CHAR(CDOPCAODIARIO) as Codigo, TO_CHAR(DEOPCAODIARIO) as Descricao
from EADMOPCAODIARIO

union

select 'ADM' as Modulo, 'PERIODICIDADE' as Dominio, TO_CHAR(CDPERIODICIDADE) as Codigo, TO_CHAR(DEPERIODICIDADE) as Descricao
from EADMPERIODICIDADE

union

select 'ADM' as Modulo, 'SITUACAOTAREFA' as Dominio, TO_CHAR(CDSITUACAOTAREFA) as Codigo, TO_CHAR(NMSITUACAOTAREFA) as Descricao
from EADMSITUACAOTAREFA

union

select 'AFA' as Modulo, 'GRUPOMOTIVOAFASTGERAL' as Dominio, TO_CHAR(CDGRUPOMOTIVOAFASTGERAL) as Codigo, TO_CHAR(DEGRUPOMOTIVOAFASTGERAL) as Descricao
from EAFAGRUPOMOTIVOAFASTGERAL

union

select 'AFA' as Modulo, 'ORIGEMOBITO' as Dominio, TO_CHAR(CDORIGEMOBITO) as Codigo, TO_CHAR(NMORIGEMOBITO) as Descricao
from EAFAORIGEMOBITO

union

select 'AFA' as Modulo, 'PERIODOVERIFICACARENCIA' as Dominio, TO_CHAR(CDPERIODOVERIFICACARENCIA) as Codigo, TO_CHAR(NMPERIODOVERIFICACARENCIA) as Descricao
from EAFAPERIODOVERIFICACARENCIA

union

select 'AFA' as Modulo, 'PROVCONTABILTIPOEVENTO' as Dominio, TO_CHAR(CDPROVCONTABILTIPOEVENTO) as Codigo, TO_CHAR(NMPROVCONTABILTIPOEVENTO) as Descricao
from EAFAPROVCONTABILTIPOEVENTO

union

select 'AFA' as Modulo, 'SITUACAOPEDIDOLP' as Dominio, TO_CHAR(CDSITUACAOPEDIDOLP) as Codigo, TO_CHAR(DESITUACAOPEDIDOLP) as Descricao
from EAFASITUACAOPEDIDOLP

union

select 'AFA' as Modulo, 'TIPOAFASTAMENTO' as Dominio, TO_CHAR(CDTIPOAFASTAMENTO) as Codigo, TO_CHAR(DETIPOAFASTAMENTO) as Descricao
from EAFATIPOAFASTAMENTO

union

select 'ARQ' as Modulo, 'SITUACAOPROCESSAMENTO' as Dominio, TO_CHAR(CDSITUACAOPROCESSAMENTO) as Codigo, TO_CHAR(NMSITUACAOPROCESSAMENTO) as Descricao
from EARQSITUACAOPROCESSAMENTO

union

select 'ATO' as Modulo, 'SITUACAOATOOFICIAL' as Dominio, TO_CHAR(CDSITUACAOATOOFICIAL) as Codigo, TO_CHAR(DESITUACAOATOOFICIAL) as Descricao
from EATOSITUACAOATOOFICIAL

union

select 'AVA' as Modulo, 'CONCEITOAVALIACAO' as Dominio, TO_CHAR(CDCONCEITOAVALIACAO) as Codigo, TO_CHAR(NMCONCEITOAVALIACAO) as Descricao
from EAVACONCEITOAVALIACAO

union

select 'BOL' as Modulo, 'NIVELSERIE' as Dominio, TO_CHAR(CDNIVELSERIE) as Codigo, TO_CHAR(NMNIVELSERIE) as Descricao
from EBOLNIVELSERIE

union

select 'BOL' as Modulo, 'SITUACAOCANDIDATOESTAGIO' as Dominio, TO_CHAR(CDSITUACAOCANDIDATO) as Codigo, TO_CHAR(NMSITUACAOCANDIDATO) as Descricao
from EBOLSITUACAOCANDIDATOESTAGIO

union

select 'BOL' as Modulo, 'TIPOEVENTO' as Dominio, TO_CHAR(CDTIPOEVENTO) as Codigo, TO_CHAR(NMTIPOEVENTO) as Descricao
from EBOLTIPOEVENTO

union

select 'BPC' as Modulo, 'BASEINCORPORACAOATIVO' as Dominio, TO_CHAR(CDBASEINCORPORACAOATIVO) as Codigo, TO_CHAR(NMBASEINCORPORACAOATIVO) as Descricao
from EBPCBASEINCORPORACAOATIVO

union

select 'BPC' as Modulo, 'FORMAPAGVANTPECUNIARIA' as Dominio, TO_CHAR(CDFORMAPAGVANTPECUNIARIA) as Codigo, TO_CHAR(DEFORMAPAGVANTPECUNIARIA) as Descricao
from EBPCFORMAPAGVANTPECUNIARIA

union

select 'BPC' as Modulo, 'SITUACAOINCORPORACAO' as Dominio, TO_CHAR(CDSITUACAOINCORPORACAO) as Codigo, TO_CHAR(NMSITUACAOINCORPORACAO) as Descricao
from EBPCSITUACAOINCORPORACAO

union

select 'BPC' as Modulo, 'TIPODATACONTAGEM' as Dominio, TO_CHAR(CDTIPODATACONTAGEM) as Codigo, TO_CHAR(NMTIPODATACONTAGEM) as Descricao
from EBPCTIPODATACONTAGEM

union

select 'BSI' as Modulo, 'TELAFILTRO' as Dominio, TO_CHAR(CDTELAFILTRO) as Codigo, TO_CHAR(NMTELAFILTRO) as Descricao
from EBSITELAFILTRO

union

select 'BSI' as Modulo, 'TIPOINFORMACAO' as Dominio, TO_CHAR(CDTIPOINFORMACAO) as Codigo, TO_CHAR(DETIPOINFORMACAO) as Descricao
from EBSITIPOINFORMACAO

union

select 'CAD' as Modulo, 'ABRANGENCIANOMEACAO' as Dominio, TO_CHAR(CDABRANGENCIANOMEACAO) as Codigo, TO_CHAR(NMABRANGENCIANOMEACAO) as Descricao
from ECADABRANGENCIANOMEACAO

union

select 'CAD' as Modulo, 'CATEGCERTRESERVISTA' as Dominio, TO_CHAR(CDCATEGCERTRESERVISTA) as Codigo, TO_CHAR(NMCATEGCERTRESERVISTA) as Descricao
from ECADCATEGCERTRESERVISTA

union

select 'CAD' as Modulo, 'CATEGORIACCG' as Dominio, TO_CHAR(CDCATEGORIACCG) as Codigo, TO_CHAR(NMCATEGORIACCG) as Descricao
from ECADCATEGORIACCG

union

select 'CAD' as Modulo, 'CATPROFISSIONAL' as Dominio, TO_CHAR(CDCATPROFISSIONAL) as Codigo, TO_CHAR(DECATPROFISSIONAL) as Descricao
from ECADCATPROFISSIONAL

union

select 'CAD' as Modulo, 'CORCABELO' as Dominio, TO_CHAR(CDCORCABELO) as Codigo, TO_CHAR(NMCORCABELO) as Descricao
from ECADCORCABELO

union

select 'CAD' as Modulo, 'COROLHO' as Dominio, TO_CHAR(CDCOROLHO) as Codigo, TO_CHAR(NMCOROLHO) as Descricao
from ECADCOROLHO

union

select 'CAD' as Modulo, 'CORPELE' as Dominio, TO_CHAR(CDCORPELE) as Codigo, TO_CHAR(NMCORPELE) as Descricao
from ECADCORPELE

union

select 'CAD' as Modulo, 'CRITERIODESEMPATE' as Dominio, TO_CHAR(CDCRITERIODESEMPATE) as Codigo, TO_CHAR(DECRITERIODESEMPATE) as Descricao
from ECADCRITERIODESEMPATE

union

select 'CAD' as Modulo, 'DETERMINACAODECISAO' as Dominio, TO_CHAR(CDDETERMINACAODECISAO) as Codigo, TO_CHAR(NMDETERMINACAODECISAO) as Descricao
from ECADDETERMINACAODECISAO

union

select 'CAD' as Modulo, 'DIASEMANA' as Dominio, TO_CHAR(CDDIASEMANA) as Codigo, TO_CHAR(NMDIASEMANA) as Descricao
from ECADDIASEMANA

union

select 'CAD' as Modulo, 'ESTADO' as Dominio, TO_CHAR(SGESTADO) as Codigo, TO_CHAR(NMESTADO) as Descricao
from ECADESTADO

union

select 'CAD' as Modulo, 'ESTADOCIVIL' as Dominio, TO_CHAR(CDESTADOCIVIL) as Codigo, TO_CHAR(NMESTADOCIVIL) as Descricao
from ECADESTADOCIVIL

union

select 'CAD' as Modulo, 'FORMARECEBCONTRACHEQUE' as Dominio, TO_CHAR(CDCONTRACHEQUE) as Codigo, TO_CHAR(NMCONTRACHEQUE) as Descricao
from ECADFORMARECEBCONTRACHEQUE

union

select 'CAD' as Modulo, 'GRAUINSTRUCAO' as Dominio, TO_CHAR(CDGRAUINSTRUCAO) as Codigo, TO_CHAR(NMGRAUINSTRUCAO) as Descricao
from ECADGRAUINSTRUCAO

union

select 'CAD' as Modulo, 'IDIOMA' as Dominio, TO_CHAR(CDIDIOMA) as Codigo, TO_CHAR(NMIDIOMA) as Descricao
from ECADIDIOMA

union

select 'CAD' as Modulo, 'MEIODIVULGACAO' as Dominio, TO_CHAR(CDMEIODIVULGACAO) as Codigo, TO_CHAR(DEMEIODIVULGACAO) as Descricao
from ECADMEIODIVULGACAO

union

select 'CAD' as Modulo, 'MEIOPUBLICACAO' as Dominio, TO_CHAR(CDMEIOPUBLICACAO) as Codigo, TO_CHAR(NMMEIOPUBLICACAO) as Descricao
from ECADMEIOPUBLICACAO

union

select 'CAD' as Modulo, 'MES' as Dominio, TO_CHAR(CDMES) as Codigo, TO_CHAR(NMMES) as Descricao
from ECADMES

union

select 'CAD' as Modulo, 'MODALIDADECOMISSAOCONSELHO' as Dominio, TO_CHAR(CDMODALIDADECOMISSAOCONSELHO) as Codigo, TO_CHAR(DEMODALIDADECOMISSAOCONSELHO) as Descricao
from ECADMODALIDADECOMISSAOCONSELHO

union

select 'CAD' as Modulo, 'MOTREJEICAOIMPENTURMACAO' as Dominio, TO_CHAR(CDMOTREJEICAOIMPENTURMACAO) as Codigo, TO_CHAR(DEMOTREJEICAOIMPENTURMACAO) as Descricao
from ECADMOTREJEICAOIMPENTURMACAO

union

select 'CAD' as Modulo, 'NATUREZAEVENTO' as Dominio, TO_CHAR(CDNATUREZAEVENTO) as Codigo, TO_CHAR(DENATUREZAEVENTO) as Descricao
from ECADNATUREZAEVENTO

union

select 'CAD' as Modulo, 'NATUREZARESCISAO' as Dominio, TO_CHAR(CDNATUREZARESCISAO) as Codigo, TO_CHAR(DENATUREZARESCISAO) as Descricao
from ECADNATUREZARESCISAO

union

select 'CAD' as Modulo, 'NATUREZAVINCULO' as Dominio, TO_CHAR(CDNATUREZAVINCULO) as Codigo, TO_CHAR(NMNATUREZAVINCULO) as Descricao
from ECADNATUREZAVINCULO

union

select 'CAD' as Modulo, 'OPCAODECLARACAOBEM' as Dominio, TO_CHAR(CDOPCAODECLARACAOBEM) as Codigo, TO_CHAR(NMOPCAODECLARACAOBEM) as Descricao
from ECADOPCAODECLARACAOBEM

union

select 'CAD' as Modulo, 'OPCAOFERIAS' as Dominio, TO_CHAR(CDOPCAOFERIAS) as Codigo, TO_CHAR(NMOPCAOFERIAS) as Descricao
from ECADOPCAOFERIAS

union

select 'CAD' as Modulo, 'OPCAOREMUNERACAO' as Dominio, TO_CHAR(CDOPCAOREMUNERACAO) as Codigo, TO_CHAR(NMOPCAOREMUNERACAO) as Descricao
from ECADOPCAOREMUNERACAO

union

select 'CAD' as Modulo, 'OPREMUNERACAO' as Dominio, TO_CHAR(CDOPCAO) as Codigo, TO_CHAR(NMOPCAO) as Descricao
from ECADOPREMUNERACAO

union

select 'CAD' as Modulo, 'ORIGEMDOCDIGITAL' as Dominio, TO_CHAR(CDORIGEMDOCDIGITAL) as Codigo, TO_CHAR(NMORIGEMDOCDIGITAL) as Descricao
from ECADORIGEMDOCDIGITAL

union

select 'CAD' as Modulo, 'PERIODOTURNO' as Dominio, TO_CHAR(CDPERIODOTURNO) as Codigo, TO_CHAR(NMPERIODOTURNO) as Descricao
from ECADPERIODOTURNO

union

select 'CAD' as Modulo, 'RACA' as Dominio, TO_CHAR(CDRACA) as Codigo, TO_CHAR(NMRACA) as Descricao
from ECADRACA

union

select 'CAD' as Modulo, 'REGIMEPREVIDENCIARIO' as Dominio, TO_CHAR(CDREGIMEPREVIDENCIARIO) as Codigo, TO_CHAR(NMREGIMEPREVIDENCIARIO) as Descricao
from ECADREGIMEPREVIDENCIARIO

union

select 'CAD' as Modulo, 'REGIMETRABALHO' as Dominio, TO_CHAR(CDREGIMETRABALHO) as Codigo, TO_CHAR(NMREGIMETRABALHO) as Descricao
from ECADREGIMETRABALHO

union

select 'CAD' as Modulo, 'RELACAOTRABALHO' as Dominio, TO_CHAR(CDRELACAOTRABALHO) as Codigo, TO_CHAR(NMRELACAOTRABALHO) as Descricao
from ECADRELACAOTRABALHO

union

select 'CAD' as Modulo, 'RELACAOVINCULO' as Dominio, TO_CHAR(CDRELACAOVINCULO) as Codigo, TO_CHAR(NMRELACAOVINCULO) as Descricao
from ECADRELACAOVINCULO

union

select 'CAD' as Modulo, 'RESULTADOPOSSE' as Dominio, TO_CHAR(CDRESULTADOPOSSE) as Codigo, TO_CHAR(DERESULTADOPOSSE) as Descricao
from ECADRESULTADOPOSSE

union

select 'CAD' as Modulo, 'SITCANDCHAMADA' as Dominio, TO_CHAR(CDSITCANDCHAMADA) as Codigo, TO_CHAR(NMSITCANDCHAMADA) as Descricao
from ECADSITCANDCHAMADA

union

select 'CAD' as Modulo, 'SITUACAOCANDIDATOCONCURSO' as Dominio, TO_CHAR(CDSITUACAOCANDIDATOCONCURSO) as Codigo, TO_CHAR(DESITUACAOCANDIDATOCONCURSO) as Descricao
from ECADSITUACAOCANDIDATOCONCURSO

union

select 'CAD' as Modulo, 'SITUACAOCANDIDATOETAPA' as Dominio, TO_CHAR(CDSITUACAOCANDIDATOETAPA) as Codigo, TO_CHAR(NMSITUACAOCANDIDATOETAPA) as Descricao
from ECADSITUACAOCANDIDATOETAPA

union

select 'CAD' as Modulo, 'SITUACAOCURSO' as Dominio, TO_CHAR(CDSITUACAOCURSO) as Codigo, TO_CHAR(NMSITUACAOCURSO) as Descricao
from ECADSITUACAOCURSO

union

select 'CAD' as Modulo, 'SITUACAOETAPA' as Dominio, TO_CHAR(CDSITUACAOETAPA) as Codigo, TO_CHAR(NMSITUACAOETAPA) as Descricao
from ECADSITUACAOETAPA

union

select 'CAD' as Modulo, 'SITUACAOFUNCIONAL' as Dominio, TO_CHAR(CDSITUACAOFUNCIONAL) as Codigo, TO_CHAR(NMSITUACAOFUNCIONAL) as Descricao
from ECADSITUACAOFUNCIONAL

union

select 'CAD' as Modulo, 'SITUACAOLOTACIONAL' as Dominio, TO_CHAR(CDSITUACAOLOTACIONAL) as Codigo, TO_CHAR(DESITUACAOLOTACIONAL) as Descricao
from ECADSITUACAOLOTACIONAL

union

select 'CAD' as Modulo, 'SITUACAOPERAQUISITIVO' as Dominio, TO_CHAR(CDSITUACAOPERAQUISITIVO) as Codigo, TO_CHAR(NMSITUACAOPERAQUISITIVO) as Descricao
from ECADSITUACAOPERAQUISITIVO

union

select 'CAD' as Modulo, 'SITUACAOPREVIDENCIARIA' as Dominio, TO_CHAR(CDSITUACAOPREVIDENCIARIA) as Codigo, TO_CHAR(NMSITUACAOPREVIDENCIARIA) as Descricao
from ECADSITUACAOPREVIDENCIARIA

union

select 'CAD' as Modulo, 'SITUACAOVINCULO' as Dominio, TO_CHAR(CDSITUACAOVINCULO) as Codigo, TO_CHAR(NMSITUACAOVINCULO) as Descricao
from ECADSITUACAOVINCULO

union

select 'CAD' as Modulo, 'TIPOAFASTAMENTO' as Dominio, TO_CHAR(CDTIPOAFASTAMENTO) as Codigo, TO_CHAR(NMTIPOAFASTAMENTO) as Descricao
from ECADTIPOAFASTAMENTO

union

select 'CAD' as Modulo, 'TIPOCABELO' as Dominio, TO_CHAR(CDTIPOCABELO) as Codigo, TO_CHAR(NMTIPOCABELO) as Descricao
from ECADTIPOCABELO

union

select 'CAD' as Modulo, 'TIPOCARGAHORARIA' as Dominio, TO_CHAR(CDTIPOCARGAHORARIA) as Codigo, TO_CHAR(NMTIPOCARGAHORARIA) as Descricao
from ECADTIPOCARGAHORARIA

union

select 'CAD' as Modulo, 'TIPOCARGOVINCULOEXTERNO' as Dominio, TO_CHAR(CDTIPOCARGOVINCULOEXTERNO) as Codigo, TO_CHAR(NMTIPOCARGOVINCULOEXTERNO) as Descricao
from ECADTIPOCARGOVINCULOEXTERNO

union

select 'CAD' as Modulo, 'TIPOCLASSIFICACAO' as Dominio, TO_CHAR(CDTIPOCLASSIFICACAO) as Codigo, TO_CHAR(NMTIPOCLASSIFICACAO) as Descricao
from ECADTIPOCLASSIFICACAO

union

select 'CAD' as Modulo, 'TIPODEFICIENCIA' as Dominio, TO_CHAR(CDTIPODEFICIENCIA) as Codigo, TO_CHAR(NMTIPODEFICIENCIA) as Descricao
from ECADTIPODEFICIENCIA

union

select 'CAD' as Modulo, 'TIPODEPENDENCIA' as Dominio, TO_CHAR(CDTIPODEPENDENCIA) as Codigo, TO_CHAR(NMTIPODEPENDENCIA) as Descricao
from ECADTIPODEPENDENCIA

union

select 'CAD' as Modulo, 'TIPODEPENDENCIAADM' as Dominio, TO_CHAR(CDTIPODEPENDENCIAADM) as Codigo, TO_CHAR(NMTIPODEPENDENCIAADM) as Descricao
from ECADTIPODEPENDENCIAADM

union

select 'CAD' as Modulo, 'TIPODEPENDENTEVINCULO' as Dominio, TO_CHAR(CDTIPODEPENDENTEVINCULO) as Codigo, TO_CHAR(DETIPODEPENDENTEVINCULO) as Descricao
from ECADTIPODEPENDENTEVINCULO

union

select 'CAD' as Modulo, 'TIPODOCUMENTODEPENDENTE' as Dominio, TO_CHAR(CDTIPODOCUMENTODEPENDENTE) as Codigo, TO_CHAR(NMTIPODOCUMENTODEPENDENTE) as Descricao
from ECADTIPODOCUMENTODEPENDENTE

union

select 'CAD' as Modulo, 'TIPODOCUMENTOPOSGRADUACAO' as Dominio, TO_CHAR(CDTIPODOCUMENTOPOSGRADUACAO) as Codigo, TO_CHAR(DETIPODOCUMENTO) as Descricao
from ECADTIPODOCUMENTOPOSGRADUACAO

union

select 'CAD' as Modulo, 'TIPOEMPRESA' as Dominio, TO_CHAR(CDTIPOEMPRESA) as Codigo, TO_CHAR(NMTIPOEMPRESA) as Descricao
from ECADTIPOEMPRESA

union

select 'CAD' as Modulo, 'TIPOENDERECO' as Dominio, TO_CHAR(CDTIPOENDERECO) as Codigo, TO_CHAR(NMTIPOENDERECO) as Descricao
from ECADTIPOENDERECO

union

select 'CAD' as Modulo, 'TIPOETAPA' as Dominio, TO_CHAR(CDTIPOETAPA) as Codigo, TO_CHAR(NMTIPOETAPA) as Descricao
from ECADTIPOETAPA

union

select 'CAD' as Modulo, 'TIPOFASECONCURSO' as Dominio, TO_CHAR(CDTIPOFASECONCURSO) as Codigo, TO_CHAR(NMTIPOFASECONCURSO) as Descricao
from ECADTIPOFASECONCURSO

union

select 'CAD' as Modulo, 'TIPOFASECURSO' as Dominio, TO_CHAR(CDTIPOFASE) as Codigo, TO_CHAR(NMTIPOFASE) as Descricao
from ECADTIPOFASECURSO

union

select 'CAD' as Modulo, 'TIPOFORMARESPONDERCARGO' as Dominio, TO_CHAR(CDTIPOFORMARESPONDERCARGO) as Codigo, TO_CHAR(DETIPOFORMARESPONDERCARGO) as Descricao
from ECADTIPOFORMARESPONDERCARGO

union

select 'CAD' as Modulo, 'TIPOFORMARESPONDERUO' as Dominio, TO_CHAR(CDTIPOFORMARESPONDERUO) as Codigo, TO_CHAR(DETIPOFORMARESPONDERUO) as Descricao
from ECADTIPOFORMARESPONDERUO

union

select 'CAD' as Modulo, 'TIPOGRADUACAO' as Dominio, TO_CHAR(CDTIPOGRADUACAO) as Codigo, TO_CHAR(NMTIPOGRADUACAO) as Descricao
from ECADTIPOGRADUACAO

union

select 'CAD' as Modulo, 'TIPOHABITACAO' as Dominio, TO_CHAR(CDTIPOHABITACAO) as Codigo, TO_CHAR(NMTIPOHABITACAO) as Descricao
from ECADTIPOHABITACAO

union

select 'CAD' as Modulo, 'TIPOHISTORICODIVERSO' as Dominio, TO_CHAR(CDTIPOHISTORICODIVERSO) as Codigo, TO_CHAR(NMTIPOHISTORICODIVERSO) as Descricao
from ECADTIPOHISTORICODIVERSO

union

select 'CAD' as Modulo, 'TIPOITEMCARREIRA' as Dominio, TO_CHAR(CDTIPOITEMCARREIRA) as Codigo, TO_CHAR(NMTIPOITEMCARREIRA) as Descricao
from ECADTIPOITEMCARREIRA

union

select 'CAD' as Modulo, 'TIPOMATRICAGRUP' as Dominio, TO_CHAR(CDTIPOMATRICAGRUP) as Codigo, TO_CHAR(NMTIPOMATRICAGRUP) as Descricao
from ECADTIPOMATRICAGRUP

union

select 'CAD' as Modulo, 'TIPOMATRICORGAO' as Dominio, TO_CHAR(CDTIPOMATRICORGAO) as Codigo, TO_CHAR(NMTIPOMATRICORGAO) as Descricao
from ECADTIPOMATRICORGAO

union

select 'CAD' as Modulo, 'TIPONECESSIDADE' as Dominio, TO_CHAR(CDTIPONECESSIDADE) as Codigo, TO_CHAR(NMTIPONECESSIDADE) as Descricao
from ECADTIPONECESSIDADE

union

select 'CAD' as Modulo, 'TIPOOCUPACAOAULA' as Dominio, TO_CHAR(CDTIPOOCUPACAOAULA) as Codigo, TO_CHAR(NMTIPOOCUPACAOAULA) as Descricao
from ECADTIPOOCUPACAOAULA

union

select 'CAD' as Modulo, 'TIPOOCUPACAOUO' as Dominio, TO_CHAR(CDTIPOOCUPACAOUO) as Codigo, TO_CHAR(NMTIPOOCUPACAOUO) as Descricao
from ECADTIPOOCUPACAOUO

union

select 'CAD' as Modulo, 'TIPOOPCAOMES' as Dominio, TO_CHAR(CDTIPOOPCAOMES) as Codigo, TO_CHAR(NMTIPOOPCAOMES) as Descricao
from ECADTIPOOPCAOMES

union

select 'CAD' as Modulo, 'TIPOQUADROLOTACIONALCEF' as Dominio, TO_CHAR(CDTIPOQUADROLOTACIONALCEF) as Codigo, TO_CHAR(NMTIPOQUADROLOTACIONALCEF) as Descricao
from ECADTIPOQUADROLOTACIONALCEF

union

select 'CAD' as Modulo, 'TIPORECEBIMENTO' as Dominio, TO_CHAR(CDTIPORECEBIMENTO) as Codigo, TO_CHAR(NMTIPORECEBIMENTO) as Descricao
from ECADTIPORECEBIMENTO

union

select 'CAD' as Modulo, 'TIPOREGRALICPRE' as Dominio, TO_CHAR(CDTIPOREGRALICPRE) as Codigo, TO_CHAR(NMTIPOREGRALICPRE) as Descricao
from ECADTIPOREGRALICPRE

union

select 'CAD' as Modulo, 'TIPOSANGUINEO' as Dominio, TO_CHAR(CDTIPOSANGUINEO) as Codigo, TO_CHAR(NMTIPOSANGUINEO) as Descricao
from ECADTIPOSANGUINEO

union

select 'CAD' as Modulo, 'TIPOTEMPOSERVICO' as Dominio, TO_CHAR(CDTIPOTEMPOSERVICO) as Codigo, TO_CHAR(NMTIPOTEMPOSERVICO) as Descricao
from ECADTIPOTEMPOSERVICO

union

select 'CAD' as Modulo, 'TPOCUPAULA' as Dominio, TO_CHAR(CDTPOCUPAULA) as Codigo, TO_CHAR(NMTPOCUPAULA) as Descricao
from ECADTPOCUPAULA

union

select 'CAD' as Modulo, 'TPOCUPCARGAHORARIA' as Dominio, TO_CHAR(CDTPOCUPCARGAHORARIA) as Codigo, TO_CHAR(NMTPOCUPCARGAHORARIA) as Descricao
from ECADTPOCUPCARGAHORARIA

union

select 'CAD' as Modulo, 'TPRELCONTRATUAL' as Dominio, TO_CHAR(CDTPRELCONTRATUAL) as Codigo, TO_CHAR(NMTPRELCONTRATUAL) as Descricao
from ECADTPRELCONTRATUAL

union

select 'CAD' as Modulo, 'TPUTILIZACAOENTURMACAO' as Dominio, TO_CHAR(CDTPUTILIZACAOENTURMACAO) as Codigo, TO_CHAR(NMUTILIZACAOENTURMACAO) as Descricao
from ECADTPUTILIZACAOENTURMACAO

union

select 'CAD' as Modulo, 'TURNO' as Dominio, TO_CHAR(CDTURNO) as Codigo, TO_CHAR(NMTURNO) as Descricao
from ECADTURNO

union

select 'CAT' as Modulo, 'MOMENTOCONCESSAO' as Dominio, TO_CHAR(CDMOMENTOCONCESSAO) as Codigo, TO_CHAR(DEMOMENTOCONCESSAO) as Descricao
from ECATMOMENTOCONCESSAO

union

select 'CAT' as Modulo, 'TIPOPONTUACAO' as Dominio, TO_CHAR(CDTIPOPONTUACAO) as Codigo, TO_CHAR(NMTIPOPONTUACAO) as Descricao
from ECATTIPOPONTUACAO

union

select 'CAT' as Modulo, 'TIPOPROGRESSAO' as Dominio, TO_CHAR(CDTIPOPROGRESSAO) as Codigo, TO_CHAR(DETIPOPROGRESSAO) as Descricao
from ECATTIPOPROGRESSAO

union

select 'EXT' as Modulo, 'PM_TAB_AREA' as Dominio, TO_CHAR(CD_AREA) as Codigo, TO_CHAR(DE_AREA) as Descricao
from EEXTPM_TAB_AREA

union

select 'EXT' as Modulo, 'PROCESSAMENTO' as Dominio, TO_CHAR(CDPROCESSAMENTO) as Codigo, TO_CHAR(NMPROCESSAMENTO) as Descricao
from EEXTPROCESSAMENTO

union

select 'EXT' as Modulo, 'SITUACAOPROCESSAMENTO' as Dominio, TO_CHAR(CDSITUACAOPROCESSAMENTO) as Codigo, TO_CHAR(NMSITUACAOPROCESSAMENTO) as Descricao
from EEXTSITUACAOPROCESSAMENTO

union

select 'EXT' as Modulo, 'TAB_REGIME' as Dominio, TO_CHAR(CD_REGIME) as Codigo, TO_CHAR(DE_REGIME) as Descricao
from EEXTTAB_REGIME

union

select 'EXT' as Modulo, 'TIPOPROCESSAMENTO' as Dominio, TO_CHAR(CDTIPOPROCESSAMENTO) as Codigo, TO_CHAR(NMTIPOPROCESSAMENTO) as Descricao
from EEXTTIPOPROCESSAMENTO

union

select 'GAR' as Modulo, 'ESTATISTICASTCETITULO' as Dominio, TO_CHAR(CDTITULO) as Codigo, TO_CHAR(NMTITULO) as Descricao
from EGARESTATISTICASTCETITULO

union

select 'GAR' as Modulo, 'SITUACAOARQUIVO' as Dominio, TO_CHAR(CDSITUACAOARQUIVO) as Codigo, TO_CHAR(NMSITUACAOARQUIVO) as Descricao
from EGARSITUACAOARQUIVO

union

select 'HLP' as Modulo, 'SITUACAOPROCEDIMENTO' as Dominio, TO_CHAR(CDSITUACAOPROCEDIMENTO) as Codigo, TO_CHAR(NMSITUACAOPROCEDIMENTO) as Descricao
from EHLPSITUACAOPROCEDIMENTO

union

select 'MOV' as Modulo, 'ABRANGENCIAMOV' as Dominio, TO_CHAR(CDABRANGENCIAMOV) as Codigo, TO_CHAR(NMABRANGENCIAMOV) as Descricao
from EMOVABRANGENCIAMOV

union

select 'MOV' as Modulo, 'CARACTERISTICAEVENTO' as Dominio, TO_CHAR(CDCARACTERISTICAEVENTO) as Codigo, TO_CHAR(DECARACTERISTICAEVENTO) as Descricao
from EMOVCARACTERISTICAEVENTO

union

select 'MOV' as Modulo, 'CRITERIOABERTURAPERIODOAQ' as Dominio, TO_CHAR(CDCRITERIOABERTURAPERIODOAQ) as Codigo, TO_CHAR(NMCRITERIOABERTURAPERIODOAQ) as Descricao
from EMOVCRITERIOABERTURAPERIODOAQ

union

select 'MOV' as Modulo, 'GRUPO' as Dominio, TO_CHAR(CDGRUPO) as Codigo, TO_CHAR(NMGRUPO) as Descricao
from EMOVGRUPO

union

select 'MOV' as Modulo, 'MEIOTRANSPORTE' as Dominio, TO_CHAR(CDMEIOTRANSPORTE) as Codigo, TO_CHAR(NMMEIOTRANSPORTE) as Descricao
from EMOVMEIOTRANSPORTE

union

select 'MOV' as Modulo, 'MODALIDADEEVENTO' as Dominio, TO_CHAR(CDMODALIDADEEVENTO) as Codigo, TO_CHAR(NMMODALIDADEEVENTO) as Descricao
from EMOVMODALIDADEEVENTO

union

select 'MOV' as Modulo, 'MODALIDADEPOLICIAMENTO' as Dominio, TO_CHAR(CDMODALIDADEPOLICIAMENTO) as Codigo, TO_CHAR(NMMODALIDADEPOLICIAMENTO) as Descricao
from EMOVMODALIDADEPOLICIAMENTO

union

select 'MOV' as Modulo, 'OBJETIVOEVENTO' as Dominio, TO_CHAR(CDOBJETIVOEVENTO) as Codigo, TO_CHAR(DEOBJETIVOEVENTO) as Descricao
from EMOVOBJETIVOEVENTO

union

select 'MOV' as Modulo, 'SITFRUICAOPERAQUISITIVO' as Dominio, TO_CHAR(CDSITFRUICAOPERAQUISITIVO) as Codigo, TO_CHAR(NMSITFRUICAOPERAQUISITIVO) as Descricao
from EMOVSITFRUICAOPERAQUISITIVO

union

select 'MOV' as Modulo, 'SITUACAOFRUICAO' as Dominio, TO_CHAR(CDSITUACAOFRUICAO) as Codigo, TO_CHAR(NMSITUACAOFRUICAO) as Descricao
from EMOVSITUACAOFRUICAO

union

select 'MOV' as Modulo, 'SITUACAOIMPREGISTROAFAST' as Dominio, TO_CHAR(CDSITUACAOIMPREGISTROAFAST) as Codigo, TO_CHAR(DESITUACAOIMPREGISTROAFAST) as Descricao
from EMOVSITUACAOIMPREGISTROAFAST

union

select 'MOV' as Modulo, 'SITUACAOPERIODOAQFERIAS' as Dominio, TO_CHAR(CDSITUACAOPERIODOAQFERIAS) as Codigo, TO_CHAR(NMSITUACAOPERIODOAQFERIAS) as Descricao
from EMOVSITUACAOPERIODOAQFERIAS

union

select 'MOV' as Modulo, 'SITUACAOPRESTACAOCONTA' as Dominio, TO_CHAR(CDSITUACAOPRESTACAOCONTA) as Codigo, TO_CHAR(NMSITUACAOPRESTACAOCONTA) as Descricao
from EMOVSITUACAOPRESTACAOCONTA

union

select 'MOV' as Modulo, 'TIPOAPURACAOFREQUENCIA' as Dominio, TO_CHAR(CDTIPOAPURACAOFREQUENCIA) as Codigo, TO_CHAR(NMTIPOAPURACAOFREQUENCIA) as Descricao
from EMOVTIPOAPURACAOFREQUENCIA

union

select 'MOV' as Modulo, 'TIPODESLOCAMENTO' as Dominio, TO_CHAR(CDTIPODESLOCAMENTO) as Codigo, TO_CHAR(NMTIPODESLOCAMENTO) as Descricao
from EMOVTIPODESLOCAMENTO

union

select 'MOV' as Modulo, 'TIPOESCALA' as Dominio, TO_CHAR(CDTIPOESCALA) as Codigo, TO_CHAR(NMTIPOESCALA) as Descricao
from EMOVTIPOESCALA

union

select 'MOV' as Modulo, 'TIPOFALTA' as Dominio, TO_CHAR(CDTIPOFALTA) as Codigo, TO_CHAR(NMTIPOFALTA) as Descricao
from EMOVTIPOFALTA

union

select 'MOV' as Modulo, 'TIPOFERIADO' as Dominio, TO_CHAR(CDTIPOFERIADO) as Codigo, TO_CHAR(NMTIPOFERIADO) as Descricao
from EMOVTIPOFERIADO

union

select 'MOV' as Modulo, 'TIPOINVESTIMENTO' as Dominio, TO_CHAR(CDTIPOINVESTIMENTO) as Codigo, TO_CHAR(DETIPOINVESTIMENTO) as Descricao
from EMOVTIPOINVESTIMENTO

union

select 'MOV' as Modulo, 'TIPOMOVIMENTACAO' as Dominio, TO_CHAR(CDTIPOMOVIMENTACAO) as Codigo, TO_CHAR(NMTIPOMOVIMENTACAO) as Descricao
from EMOVTIPOMOVIMENTACAO

union

select 'MOV' as Modulo, 'TIPOPAGAMENTOFREQUENCIA' as Dominio, TO_CHAR(CDTIPOPAGAMENTOFREQUENCIA) as Codigo, TO_CHAR(NMTIPOPAGAMENTOFREQUENCIA) as Descricao
from EMOVTIPOPAGAMENTOFREQUENCIA

union

select 'MOV' as Modulo, 'TIPOREGISTROENTURMACAO' as Dominio, TO_CHAR(CDTIPOREGISTROENTURMACAO) as Codigo, TO_CHAR(NMTIPOREGISTROENTURMACAO) as Descricao
from EMOVTIPOREGISTROENTURMACAO

union

select 'MOV' as Modulo, 'TIPOREGISTROESCALA' as Dominio, TO_CHAR(CDTIPOREGISTROESCALA) as Codigo, TO_CHAR(NMTIPOREGISTROESCALA) as Descricao
from EMOVTIPOREGISTROESCALA

union

select 'MOV' as Modulo, 'TIPOREGISTROJORNADA' as Dominio, TO_CHAR(CDTIPOREGISTROJORNADA) as Codigo, TO_CHAR(NMTIPOREGISTROJORNADA) as Descricao
from EMOVTIPOREGISTROJORNADA

union

select 'MOV' as Modulo, 'VALIDADE' as Dominio, TO_CHAR(CDVALIDADE) as Codigo, TO_CHAR(NMVALIDADE) as Descricao
from EMOVVALIDADE

union

select 'PAG' as Modulo, 'CONSIGAUTACESSOFUNC' as Dominio, TO_CHAR(CDCONSIGNATARIAAUTACESSO) as Codigo, TO_CHAR(CDFUNCIONALIDADE) as Descricao
from EPAGCONSIGAUTACESSOFUNC

union

select 'PAG' as Modulo, 'GRUPOEMPENHO' as Dominio, TO_CHAR(CDGRUPOEMPENHO) as Codigo, TO_CHAR(DEGRUPOEMPENHO) as Descricao
from EPAGGRUPOEMPENHO

union

select 'PAG' as Modulo, 'MODALIDADECONSIGNATARIA' as Dominio, TO_CHAR(CDMODALIDADECONSIGNATARIA) as Codigo, TO_CHAR(NMMODALIDADECONSIGNATARIA) as Descricao
from EPAGMODALIDADECONSIGNATARIA

union

select 'PAG' as Modulo, 'MOTIVOREJEICAORRA' as Dominio, TO_CHAR(CDMOTIVOREJEICAORRA) as Codigo, TO_CHAR(DEMOTIVOREJEICAORRA) as Descricao
from EPAGMOTIVOREJEICAORRA

union

select 'PAG' as Modulo, 'ORIGEMCONSIGNACAO' as Dominio, TO_CHAR(CDORIGEMCONSIGNACAO) as Codigo, TO_CHAR(NMORIGEMCONSIGNACAO) as Descricao
from EPAGORIGEMCONSIGNACAO

union

select 'PAG' as Modulo, 'PERIODOAFASTAMENTO' as Dominio, TO_CHAR(NMPERIODOAFASTAMENTO) as Codigo, TO_CHAR(CDPERIODOAFASTAMENTO) as Descricao
from EPAGPERIODOAFASTAMENTO

union

select 'PAG' as Modulo, 'RUBPROPORCIONALIDADECHO' as Dominio, TO_CHAR(CDRUBPROPORCIONALIDADECHO) as Codigo, TO_CHAR(NMRUBPROPORCIONALIDADECHO) as Descricao
from EPAGRUBPROPORCIONALIDADECHO

union

select 'PAG' as Modulo, 'TIPOBLOQUEIO' as Dominio, TO_CHAR(CDTIPOBLOQUEIO) as Codigo, TO_CHAR(NMTIPOBLOQUEIO) as Descricao
from EPAGTIPOBLOQUEIO

union

select 'PAG' as Modulo, 'TIPOEVENTOVINCULO' as Dominio, TO_CHAR(CDTIPOEVENTOVINCULO) as Codigo, TO_CHAR(NMTIPOEVENTOVINCULO) as Descricao
from EPAGTIPOEVENTOVINCULO

union

select 'PAG' as Modulo, 'TIPOFOLHA' as Dominio, TO_CHAR(CDTIPOFOLHA) as Codigo, TO_CHAR(NMTIPOFOLHA) as Descricao
from EPAGTIPOFOLHA

union

select 'PAG' as Modulo, 'TIPOLIQUIDACAO' as Dominio, TO_CHAR(CDTIPOLIQUIDACAO) as Codigo, TO_CHAR(NMTIPOLIQUIDACAO) as Descricao
from EPAGTIPOLIQUIDACAO

union

select 'PAG' as Modulo, 'TIPOREPRESENTACAO' as Dominio, TO_CHAR(CDTIPOREPRESENTACAO) as Codigo, TO_CHAR(NMTIPOREPRESENTACAO) as Descricao
from EPAGTIPOREPRESENTACAO

union

select 'PAG' as Modulo, 'TIPOTRIBUTACAOIRRF' as Dominio, TO_CHAR(CDTIPOTRIBUTACAOIRRF) as Codigo, TO_CHAR(NMTIPOTRIBUTACAOIRRF) as Descricao
from EPAGTIPOTRIBUTACAOIRRF

union

select 'PVD' as Modulo, 'ESPECIALIDADE' as Dominio, TO_CHAR(CDESPECIALIDADE) as Codigo, TO_CHAR(NMESPECIALIDADE) as Descricao
from EPVDESPECIALIDADE

union

select 'PVD' as Modulo, 'FORMARECADASTRAMENTO' as Dominio, TO_CHAR(DEFORMARECADASTRAMENTO) as Codigo, TO_CHAR(CDFORMARECADASTRAMENTO) as Descricao
from EPVDFORMARECADASTRAMENTO

union

select 'PVD' as Modulo, 'FORMULARIOCONSULTAMEDICA' as Dominio, TO_CHAR(CDFORMULARIOCONSULTAMEDICA) as Codigo, TO_CHAR(NMFORMULARIO) as Descricao
from EPVDFORMULARIOCONSULTAMEDICA

union

select 'PVD' as Modulo, 'GRAUATIVIDADE' as Dominio, TO_CHAR(CDGRAUATIVIDADE) as Codigo, TO_CHAR(NMGRAUATIVIDADE) as Descricao
from EPVDGRAUATIVIDADE

union

select 'PVD' as Modulo, 'LAUDOENQUADRAMENTOLEGAL' as Dominio, TO_CHAR(CDLAUDOENQUADRAMENTOLEGAL) as Codigo, TO_CHAR(DELAUDOENQUADRAMENTOLEGAL) as Descricao
from EPVDLAUDOENQUADRAMENTOLEGAL

union

select 'PVD' as Modulo, 'LOCALPERICIAMEDICA' as Dominio, TO_CHAR(CDLOCALPERICIAMEDICA) as Codigo, TO_CHAR(NMLOCALPERICIAMEDICA) as Descricao
from EPVDLOCALPERICIAMEDICA

union

select 'PVD' as Modulo, 'OPCAOHOMOLOGACAOLAUDO' as Dominio, TO_CHAR(CDOPCAOHOMOLOGACAOLAUDO) as Codigo, TO_CHAR(NMOPCAOHOMOLOGACAOLAUDO) as Descricao
from EPVDOPCAOHOMOLOGACAOLAUDO

union

select 'PVD' as Modulo, 'ORIGEMBASECALCULO' as Dominio, TO_CHAR(CDORIGEMBASECALCULO) as Codigo, TO_CHAR(NMORIGEMBASECALCULO) as Descricao
from EPVDORIGEMBASECALCULO

union

select 'PVD' as Modulo, 'SITUACAOCTC' as Dominio, TO_CHAR(CDSITUACAOCTC) as Codigo, TO_CHAR(NMSITUACAOCTC) as Descricao
from EPVDSITUACAOCTC

union

select 'PVD' as Modulo, 'SITUACAOLAUDO' as Dominio, TO_CHAR(CDSITUACAOLAUDO) as Codigo, TO_CHAR(NMSITUACAOLAUDO) as Descricao
from EPVDSITUACAOLAUDO

union

select 'PVD' as Modulo, 'SITUACAOSOLPERMEDICA' as Dominio, TO_CHAR(CDSITUACAOSOLPERMEDICA) as Codigo, TO_CHAR(NMSITUACAOSOLPERMEDICA) as Descricao
from EPVDSITUACAOSOLPERMEDICA

union

select 'PVD' as Modulo, 'SITUACAOTRAMITETCE' as Dominio, TO_CHAR(CDSITUACAOTRAMITETCE) as Codigo, TO_CHAR(NMSITUACAOTRAMITETCE) as Descricao
from EPVDSITUACAOTRAMITETCE

union

select 'PVD' as Modulo, 'TEMPOEFEITOCONTAGEM' as Dominio, TO_CHAR(CDTEMPOEFEITOCONTAGEM) as Codigo, TO_CHAR(NMTEMPOEFEITOCONTAGEM) as Descricao
from EPVDTEMPOEFEITOCONTAGEM

union

select 'PVD' as Modulo, 'TIPOATIVIDADE' as Dominio, TO_CHAR(CDTIPOATIVIDADE) as Codigo, TO_CHAR(NMTIPOATIVIDADE) as Descricao
from EPVDTIPOATIVIDADE

union

select 'PVD' as Modulo, 'TIPOEXAME' as Dominio, TO_CHAR(CDTIPOEXAME) as Codigo, TO_CHAR(NMTIPOEXAME) as Descricao
from EPVDTIPOEXAME

union

select 'PVD' as Modulo, 'TIPOOCORRENCIAFUNCIONAL' as Dominio, TO_CHAR(CDTIPOOCORRENCIAFUNCIONAL) as Codigo, TO_CHAR(NMTIPOOCORRENCIAFUNCIONAL) as Descricao
from EPVDTIPOOCORRENCIAFUNCIONAL

union

select 'PVD' as Modulo, 'TIPOPROCEDIMENTO' as Dominio, TO_CHAR(CDTIPOPROCEDIMENTO) as Codigo, TO_CHAR(NMTIPOPROCEDIMENTO) as Descricao
from EPVDTIPOPROCEDIMENTO

union

select 'PVD' as Modulo, 'TIPOSERVIDOR' as Dominio, TO_CHAR(CDTIPOSERVIDOR) as Codigo, TO_CHAR(DETIPOSERVIDOR) as Descricao
from EPVDTIPOSERVIDOR

union

select 'PVD' as Modulo, 'TIPOTEMPOESPECIAL' as Dominio, TO_CHAR(CDTIPOTEMPOESPECIAL) as Codigo, TO_CHAR(NMTIPOTEMPOESPECIAL) as Descricao
from EPVDTIPOTEMPOESPECIAL

union

select 'PVD' as Modulo, 'TIPOTEMPONORMAL' as Dominio, TO_CHAR(CDTIPOTEMPONORMAL) as Codigo, TO_CHAR(NMTIPOTEMPONORMAL) as Descricao
from EPVDTIPOTEMPONORMAL

union

select 'RDI' as Modulo, 'CLASSIFICACAOPUNICAO' as Dominio, TO_CHAR(CDCLASSIFICACAOPUNICAO) as Codigo, TO_CHAR(NMCLASSIFICACAOPUNICAO) as Descricao
from ERDICLASSIFICACAOPUNICAO

union

select 'RDI' as Modulo, 'COMPORTAMENTO' as Dominio, TO_CHAR(CDCOMPORTAMENTO) as Codigo, TO_CHAR(NMCOMPORTAMENTO) as Descricao
from ERDICOMPORTAMENTO

union

select 'RDI' as Modulo, 'EVENTOCLASSIFICACAO' as Dominio, TO_CHAR(CDEVENTOCLASSIFICACAO) as Codigo, TO_CHAR(NMEVENTOCLASSIFICACAO) as Descricao
from ERDIEVENTOCLASSIFICACAO

union

select 'RDI' as Modulo, 'SITUACAOPUNICAO' as Dominio, TO_CHAR(CDSITUACAOPUNICAO) as Codigo, TO_CHAR(NMSITUACAOPUNICAO) as Descricao
from ERDISITUACAOPUNICAO

union

select 'RDI' as Modulo, 'TIPOOCORRENCIADISCIPLINAR' as Dominio, TO_CHAR(CDTIPOOCORRENCIADISCIPLINAR) as Codigo, TO_CHAR(NMTIPOOCORRENCIADISCIPLINAR) as Descricao
from ERDITIPOOCORRENCIADISCIPLINAR

union

select 'RDI' as Modulo, 'TIPOPUNICAO' as Dominio, TO_CHAR(CDTIPOPUNICAO) as Codigo, TO_CHAR(NMTIPOPUNICAO) as Descricao
from ERDITIPOPUNICAO

union

select 'RDI' as Modulo, 'TIPOSITUACAOAGRAVANTE' as Dominio, TO_CHAR(CDTIPOSITUACAOAGRAVANTE) as Codigo, TO_CHAR(NMTIPOSITUACAOAGRAVANTE) as Descricao
from ERDITIPOSITUACAOAGRAVANTE

union

select 'RDI' as Modulo, 'TIPOSITUACAORECURSO' as Dominio, TO_CHAR(CDTIPOSITUACAORECURSO) as Codigo, TO_CHAR(NMTIPOSITUACAORECURSO) as Descricao
from ERDITIPOSITUACAORECURSO

union

select 'REP' as Modulo, 'SITUACAOPROCESSO' as Dominio, TO_CHAR(CDSITUACAOPROCESSO) as Codigo, TO_CHAR(NMSITUACAOPROCESSO) as Descricao
from EREPSITUACAOPROCESSO

union

select 'RET' as Modulo, 'SITUACAOPROCESSO' as Dominio, TO_CHAR(CDSITUACAOPROCESSO) as Codigo, TO_CHAR(NMSITUACAOPROCESSO) as Descricao
from ERETSITUACAOPROCESSO

union

select 'SAU' as Modulo, 'AVALIACAOACIDENTE' as Dominio, TO_CHAR(CDAVALIACAOACIDENTE) as Codigo, TO_CHAR(NMAVALIACAOACIDENTE) as Descricao
from ESAUAVALIACAOACIDENTE

union

select 'SAU' as Modulo, 'GRAURISCO' as Dominio, TO_CHAR(CDGRAURISCO) as Codigo, TO_CHAR(NMGRAURISCO) as Descricao
from ESAUGRAURISCO

union

select 'SAU' as Modulo, 'REGRAPRORROGAINSCRICAO' as Dominio, TO_CHAR(CDREGRAPRORROGAINSCRICAO) as Codigo, TO_CHAR(NMREGRAPRORROGAINSCRICAO) as Descricao
from ESAUREGRAPRORROGAINSCRICAO

union

select 'SAU' as Modulo, 'SITUACAOCOMUNICADO' as Dominio, TO_CHAR(CDSITUACAOCOMUNICADO) as Codigo, TO_CHAR(NMSITUACAOCOMUNICADO) as Descricao
from ESAUSITUACAOCOMUNICADO

union

select 'SAU' as Modulo, 'TIPOACIDENTE' as Dominio, TO_CHAR(CDTIPOACIDENTE) as Codigo, TO_CHAR(NMTIPOACIDENTE) as Descricao
from ESAUTIPOACIDENTE

union

select 'SAU' as Modulo, 'TIPOMOTIVOCANCELPLANO' as Dominio, TO_CHAR(CDTIPOMOTIVOCANCELPLANO) as Codigo, TO_CHAR(NMTIPOMOTIVOCANCELPLANO) as Descricao
from ESAUTIPOMOTIVOCANCELPLANO

union

select 'SEG' as Modulo, 'EVENTO' as Dominio, TO_CHAR(CDEVENTO) as Codigo, TO_CHAR(NMEVENTO) as Descricao
from ESEGEVENTO

union

select 'SEG' as Modulo, 'OPERACAO' as Dominio, TO_CHAR(CDOPERACAO) as Codigo, TO_CHAR(NMOPERACAO) as Descricao
from ESEGOPERACAO

union

select 'SEG' as Modulo, 'OPERACAOABRANGENCIA' as Dominio, TO_CHAR(CDOPERACAOABRANGENCIA) as Codigo, TO_CHAR(NMOPERACAOABRANGENCIA) as Descricao
from ESEGOPERACAOABRANGENCIA

union

select 'SEG' as Modulo, 'PRIORIDADESOLICITACAO' as Dominio, TO_CHAR(CDPRIORIDADESOLICITACAO) as Codigo, TO_CHAR(DEPRIORIDADESOLICITACAO) as Descricao
from ESEGPRIORIDADESOLICITACAO

union

select 'SEG' as Modulo, 'SITUACAOACESSO' as Dominio, TO_CHAR(CDSITUACAOACESSO) as Codigo, TO_CHAR(NMSITUACAOACESSO) as Descricao
from ESEGSITUACAOACESSO

union

select 'SEG' as Modulo, 'SITUACAOSOLICITACAO' as Dominio, TO_CHAR(CDSITUACAOSOLICITACAO) as Codigo, TO_CHAR(DESITUACAOSOLICITACAO) as Descricao
from ESEGSITUACAOSOLICITACAO

union

select 'SEG' as Modulo, 'TIPOSOLICITACAO' as Dominio, TO_CHAR(CDTIPOSOLICITACAO) as Codigo, TO_CHAR(NMTIPOSOLICITACAO) as Descricao
from ESEGTIPOSOLICITACAO

union

select 'SEG' as Modulo, 'TIPOUSUARIO' as Dominio, TO_CHAR(CDTIPOUSUARIO) as Codigo, TO_CHAR(NMTIPOUSUARIO) as Descricao
from ESEGTIPOUSUARIO

union

select 'SOC' as Modulo, 'AMBIENTE' as Dominio, TO_CHAR(CDAMBIENTE) as Codigo, TO_CHAR(NMAMBIENTE) as Descricao
from ESOCAMBIENTE

union

select 'SOC' as Modulo, 'GRUPOEVENTO' as Dominio, TO_CHAR(CDGRUPOEVENTO) as Codigo, TO_CHAR(DEGRUPOEVENTO) as Descricao
from ESOCGRUPOEVENTO

union

select 'SOC' as Modulo, 'SITUACAOEVENTO' as Dominio, TO_CHAR(CDSITUACAOEVENTO) as Codigo, TO_CHAR(DESITUACAOEVENTO) as Descricao
from ESOCSITUACAOEVENTO

union

select 'SOC' as Modulo, 'SITUACAOLOTE' as Dominio, TO_CHAR(CDSITUACAOLOTE) as Codigo, TO_CHAR(DESITUACAOLOTE) as Descricao
from ESOCSITUACAOLOTE

union

select 'SOC' as Modulo, 'TIPOFOLHACLASSIF' as Dominio, TO_CHAR(CDTIPOFOLHAPAGAMENTO) as Codigo, TO_CHAR(INTIPOFOLHACLASSIF) as Descricao
from ESOCTIPOFOLHACLASSIF

union

select 'TRB' as Modulo, 'SITREGISTROISENCAO' as Dominio, TO_CHAR(CDSITREGISTROISENCAO) as Codigo, TO_CHAR(NMSITREGISTROISENCAO) as Descricao
from ETRBSITREGISTROISENCAO

union

select 'TRB' as Modulo, 'TIPOTRIBUTACAOIPESC' as Dominio, TO_CHAR(CDTIPOTRIBUTACAOIPESC) as Codigo, TO_CHAR(NMTIPOTRIBUTACAOIPESC) as Descricao
from ETRBTIPOTRIBUTACAOIPESC

union

select 'VTR' as Modulo, 'TIPOCANCELAMENTO' as Dominio, TO_CHAR(CDTIPOCANCELAMENTO) as Codigo, TO_CHAR(DETIPOCANCELAMENTO) as Descricao
from EVTRTIPOCANCELAMENTO

union

select 'VTR' as Modulo, 'TIPODISTRIBUICAO' as Dominio, TO_CHAR(CDTIPODISTRIBUICAO) as Codigo, TO_CHAR(DETIPODISTRIBUICAO) as Descricao
from EVTRTIPODISTRIBUICAO

union

select 'VTR' as Modulo, 'TIPOTRAJETO' as Dominio, TO_CHAR(CDTIPOTRAJETO) as Codigo, TO_CHAR(NMTIPOTRAJETO) as Descricao
from EVTRTIPOTRAJETO

order by 1, 2, 3