--insert into ecadpessoa
with 
pessoa as (
select
 t1.nucpf,
 to_date(t1.dtnascimento, 'rrrr-mm-dd') dtnascimento,
 upper(t1.flsexo) flsexo,
 translate(trim(upper(t1.nmpessoa)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') nmpessoa,
 substr(translate(trim(upper(t1.nmusual)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO'), 1, 50) nmusual,
 substr(translate(trim(upper(t1.nmpessoa)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO'), 1, 40) nmreduzido,
 translate(trim(upper(t1.nmpessoa)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') nmrais,
 translate(trim(upper(t1.nmpai)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') nmpai,
 translate(trim(upper(t1.nmmae)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') nmmae,
 (select min(cdpais) from SIGRH.ECADPAIS t2 where t2.nmpais = translate(trim(upper(t1.nmpais)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdpais,
 (select min(sgestado) from SIGRH.ECADESTADO t2 where t2.sgestado = translate(trim(upper(t1.sgestado)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) sgestado,
 (select min(cdlocalidade) from SIGRH.ECADLOCALIDADE t2, SIGRH.ECADESTADO t3 where t2.nmlocalidade = translate(trim(upper(t1.nmlocalidadenasc)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') and t2.sgestado = t3.sgestado and t3.sgestado = translate(trim(upper(t1.sgestado)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdmunicipionasc,
 (select min(cdestadocivil) from SIGRH.ECADESTADOCIVIL t2 where translate(trim(upper(t2.nmestadocivil)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmestadocivil)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdestadocivil,
 (select min(cdraca) from SIGRH.ECADRACA t2 where translate(trim(upper(t2.nmraca)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmraca)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdraca,
 to_date(t1.dtnaturalizacao, 'rrrr-mm-dd') dtnaturalizacao,
 substr(lower(t1.deemail), 1, 200) deemail,
 substr(lower(t1.nucarteiraidentidade), 1, 13) nucarteiraidentidade,
 (select min(cdorgaoemissor) from SIGRH.ECADORGAOEMISSOR t2 where t2.sgorgaoemissor = translate(trim(upper(t1.sgorgaoemissor)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdorgaoemissor,
 (select min(sgestado) from SIGRH.ECADESTADO t2 where t2.sgestado = translate(trim(upper(t1.sgestadoci)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) sgestadoci,
 to_date(t1.dtexpedicao, 'rrrr-mm-dd') dtexpedicao,
 (select min(cdpais) from SIGRH.ECADPAIS t2 where t2.nmpais = translate(trim(upper(t1.nmpaisorigem)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdpaisorigem,
 to_date(t1.dtentrada, 'rrrr-mm-dd') dtentrada,
 to_date(t1.dtlimiteperm, 'rrrr-mm-dd') dtlimiteperm,
 (select min(cdtiponecessidade) from SIGRH.ECADTIPONECESSIDADE t2 where translate(trim(upper(t2.nmtiponecessidade)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmtiponecessidade)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdtiponecessidade,
 (select min(cdtipodeficiencia) from SIGRH.ECADTIPODEFICIENCIA t2 where translate(trim(upper(t2.nmtipodeficiencia)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmtipodeficiencia)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdtipodeficiencia,
 (select min(cdtipohabitacao) from SIGRH.ECADTIPOHABITACAO t2 where translate(trim(upper(t2.nmtipohabitacao)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmtipohabitacao)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdtipohabitacao,
 12 cdendereco, -- SEGAD
 null cdenderecocorresp,
 nudddres,
 nutelefoneres,
 nudddcont,
 nutelefonecont,
 nudddcel,
 nucelular,
 nupis,
 to_date(t1.dtcadastropis, 'rrrr-mm-dd') dtcadastropis,
 nureservista,
 sgorgaoreservista,
 deunidade,
 nuano,
 to_date(t1.dtemissaoreservista, 'rrrr-mm-dd') dtemissaoreservista,
 sgestadoreservista,
 nutitulo,
 nuzona,
 nusecao, 
 to_date(t1.dtemissaotitulo, 'rrrr-mm-dd') dtemissaotitulo,
 (select min(cdlocalidade) from SIGRH.ECADLOCALIDADE t2, SIGRH.ECADESTADO t3 where t2.nmlocalidade = translate(trim(upper(t1.nmlocalidadetitulo)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') and t2.sgestado = t3.sgestado and t3.sgestado = translate(trim(upper(t1.sgestado)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdmunicipiotitulo,
 nucarteirahab,
 nmcategoria,
 sgestadohabilitacao,
 to_date(t1.dtprimhabilitacao, 'rrrr-mm-dd') dtprimhabilitacao,
 to_date(t1.dtvalidadehabilitacao, 'rrrr-mm-dd') dtvalidadehabilitacao,
 nunit,
 (select min(cdocupacao) from SIGRH.ECADOCUPACAO t2 where t2.nuocupacao = t1.nuocupacao) cdocupacao,
 to_date(t1.dtinicioemprego, 'rrrr-mm-dd') dtinicioemprego, 
 to_date(t1.dtfimemprego, 'rrrr-mm-dd') dtfimemprego, 
 (select min(cdtipoempresa) from SIGRH.ECADTIPOEMPRESA t2 where translate(trim(upper(t2.nmtipoempresa)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmtipoempresa)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdtipoempresa, 
 (select min(cdfatorrh) from SIGRH.ECADFATORRH t2 where translate(trim(upper(t2.nmfatorrh)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmfatorrh)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdfatorrh, 
 nunis, 
 (select min(cdtiposanguineo) from SIGRH.ECADTIPOSANGUINEO t2 where t2.nmtiposanguineo = t1.nmtiposanguineo) cdtiposanguineo, 
 (select min(cdcategcertreservista) from SIGRH.ECADCATEGCERTRESERVISTA t2 where translate(trim(upper(t2.nmcategcertreservista)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmcategcertreservista)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdcategcertreservista, 
 (select min(cdregiaomilitar) from SIGRH.ECADREGIAOMILITAR t2 where translate(trim(upper(t2.nmregiaomilitar)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmregiaomilitar)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdregiaomilitar, 
 (select min(cdcircunscricao) from SIGRH.ECADCIRCUNSCRICAO t2 where translate(trim(upper(t2.nmcircunscricao)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmcircunscricao)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdcircunscricao, 
 (select min(cdregimetrabalho) from SIGRH.ECADREGIMETRABALHO t2 where translate(trim(upper(t2.nmregimetrabalho)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmregimetrabalho)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdregimetrabalho, 
 (select min(cdregimeprevidenciario) from SIGRH.ECADREGIMEPREVIDENCIARIO t2 where translate(trim(upper(t2.nmregimeprevidenciario)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') = translate(trim(upper(t1.nmregimeprevidenciario)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) cdregimeprevidenciario, 
 nuserie,
 (select min(sgestado) from SIGRH.ECADESTADO t2 where t2.sgestado = translate(trim(upper(t1.sgestadotitulo)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')) sgestadotitulo,
 flvagadeficiente,
 nrrne,
 orgaoemissorrne, 
 to_date(t1.dtexpedicaorne, 'rrrr-mm-dd') dtexpedicaorne, 
 classtrabestrangeiro, nmsocial
from sigrhmig.emigpessoa t1
where dtnascimento is not null
  and flsexo is not null
  and nmpessoa is not null
  and nmmae is not null
  and nmpais is not null
  and nmestadocivil is not null
  and nmraca is not null
  and exists (select * from SIGRH.ECADPAIS t2
              where translate(trim(upper(t2.nmpais)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')
                  = translate(trim(upper(t1.nmpais)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO'))
  and exists (select * from SIGRH.ECADESTADOCIVIL t2
              where translate(trim(upper(t2.nmestadocivil)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO')
                  = translate(trim(upper(t1.nmestadocivil)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO'))
  and exists (select * from SIGRH.ECADRACA t2
              where translate(trim(upper(t2.nmraca)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO') =
                    translate(trim(upper(t1.nmraca)), 'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕ', 'ACEIOUAEIOUAEIOUAO'))
  and not exists (select * from SIGRH.ECADPESSOA t2
                  where t1.nucpf = t2.nucpf
                    and t1.dtnascimento = to_char(t2.dtnascimento, 'rrrr-mm-dd')
                    and t1.flsexo = t2.flsexo)
)

select
 ownum + 23 as cdpessoa,
 nucpf,
 dtnascimento,
 flsexo,
 nmpessoa,
 nmusual,
 nmreduzido,
 nmrais,
 nmpai,
 nmmae,
 cdpais,
 sgestado,
 cdmunicipionasc,
 cdestadocivil,
 cdraca,
 dtnaturalizacao,
 deemail,
 nucarteiraidentidade,
 cdorgaoemissor,
 sgestadoci,
 dtexpedicao,
 cdpaisorigem,
 dtentrada,
 dtlimiteperm,
 cdtiponecessidade,
 cdtipodeficiencia,
 cdtipohabitacao,
 cdendereco,
 cdenderecocorresp,
 nudddres,
 nutelefoneres,
 nudddcont,
 nutelefonecont,
 nudddcel,
 nucelular,
 nupis,
 dtcadastropis,
 nureservista,
 sgorgaoreservista,
 deunidade,
 nuano,
 dtemissaoreservista,
 sgestadoreservista,
 nutitulo,
 nuzona,
 nusecao,
 dtemissaotitulo,
 cdmunicipiotitulo,
 nucarteirahab,
 nmcategoria,
 sgestadohabilitacao,
 dtprimhabilitacao,
 dtvalidadehabilitacao,
 nunit,
 cdocupacao,
 dtinicioemprego,
 dtfimemprego,
 cdtipoempresa,
 '11111111111' as nucpfcadastrador,
 sysdate as dtinclusao,
 null as cdautacessoultalt,
 null as nubase,
 systimestamp as dtultalteracao,
 1 as nupessoa,
 null as dtinscrplanosaude,
 'S' as flmesmoendereco,
 cdfatorrh,
 nunis,
 1 as nudvpessoa,
 cdtiposanguineo,
 cdcategcertreservista,
 cdregiaomilitar,
 cdcircunscricao,
 cdregimetrabalho,
 cdregimeprevidenciario,
 '11111111111' as nucpfultalteracao,
 null as cdorgaoultalteracao,
 null as nuserie,
 sgestadotitulo,
 'N' as flreabilitada,
 nvl(flvagadeficiente, 'N') as flvagadeficiente,
 nrrne,
 orgaoemissorrne,
 dtexpedicaorne,
 classtrabestrangeiro,
 nmsocial
from pessoa