
-- Selecionando rubricas do sistema

SELECT CDTIPORUBRICA, NURUBRICA, HR.DERUBRICA
  FROM EPAGRUBRICA R
 INNER JOIN EPAGHISTRUBRICA HR
    ON R.CDRUBRICA = HR.CDRUBRICA
 WHERE (HR.NUANOINICIOVIGENCIA * 100 + HR.NUMESINICIOVIGENCIA) < = 202001
   AND (HR.NUANOFIMVIGENCIA * 100 + HR.NUMESFIMVIGENCIA >= 202001 OR
       HR.NUANOFIMVIGENCIA IS NULL);

-- Selecionando rubricas do agrupamento

SELECT CDTIPORUBRICA, NURUBRICA, HRA.DERUBRICAAGRUPAMENTO
  FROM EPAGRUBRICA R
 INNER JOIN EPAGRUBRICAAGRUPAMENTO RA
    ON R.CDRUBRICA = RA.CDRUBRICA
 INNER JOIN EPAGHISTRUBRICAAGRUPAMENTO HRA
    ON HRA.CDRUBRICAAGRUPAMENTO = RA.CDRUBRICAAGRUPAMENTO
 WHERE (HRA.NUANOINICIOVIGENCIA * 100 + HRA.NUMESINICIOVIGENCIA) < = 202001
   AND (HRA.NUANOFIMVIGENCIA * 100 + HRA.NUMESFIMVIGENCIA >= 202001 OR
       HRA.NUANOFIMVIGENCIA IS NULL);
