-- Selecionando informações de cargos efetivos que possuem cargos em comissão

SELECT V.NUMATRICULA || '-' || NUDVMATRICULA || '-' || NUSEQMATRICULA,
       P.NMPESSOA,
       P.DTNASCIMENTO,
       V.DTADMISSAO,
       D.DECARGOCOMISSIONADO,
       E.NUREFERENCIA,
       E.NUNIVEL,
       O.SGORGAO,
       U.NMUNIDADEORGANIZACIONAL
  FROM ECADVINCULO V
 INNER JOIN ECADHISTCARGOCOM E
    ON E.CDVINCULO = V.CDVINCULO
 INNER JOIN ECADCARGOCOMISSIONADO CCO
    ON CCO.CDCARGOCOMISSIONADO = E.CDCARGOCOMISSIONADO
 INNER JOIN ECADEVOLUCAOCARGOCOMISSIONADO D
    ON D.CDCARGOCOMISSIONADO = E.CDCARGOCOMISSIONADO
 INNER JOIN ECADLOCALTRABALHO LT
    ON LT.CDHISTCARGOCOM = E.CDHISTCARGOCOM
 INNER JOIN VCADUNIDADEORGANIZACIONAL U
    ON U.CDUNIDADEORGANIZACIONAL = LT.CDUNIDADEORGANIZACIONAL
 INNER JOIN VCADORGAO O
    ON O.CDORGAO = U.CDORGAO
 INNER JOIN ECADPESSOA P
    ON P.CDPESSOA = V.CDPESSOA
 INNER JOIN ECADRELACAOTRABALHO RT
    ON RT.CDRELACAOTRABALHO = E.CDRELACAOTRABALHO
 WHERE (E.DTINICIO < SYSDATE)
   AND (E.DTFIM IS NULL OR E.DTFIM > SYSDATE)
   AND EXISTS
 (SELECT 1 FROM ECADHISTCARGOEFETIVO G WHERE G.CDVINCULO = V.CDVINCULO)