 -- Selecionando informações do cargo efetivo
 
SELECT V.NUMATRICULA || '-' || NUDVMATRICULA || '-' || NUSEQMATRICULA,
       P.NMPESSOA,
       P.DTNASCIMENTO,
       V.DTADMISSAO,
       C.DEITEMCARREIRA,
       RT.NMRELACAOTRABALHO
  FROM ECADVINCULO V
 INNER JOIN ECADHISTCARGOEFETIVO E
    ON E.CDVINCULO = V.CDVINCULO
 INNER JOIN ECADESTRUTURACARREIRA ES
    ON ES.CDESTRUTURACARREIRA = E.CDESTRUTURACARREIRA
 INNER JOIN ECADITEMCARREIRA C
    ON C.CDITEMCARREIRA = ES.CDITEMCARREIRA
 INNER JOIN ECADPESSOA P
    ON P.CDPESSOA = V.CDPESSOA
 INNER JOIN ECADRELACAOTRABALHO RT
    ON RT.CDRELACAOTRABALHO = E.CDRELACAOTRABALHO
 WHERE (E.DTINICIO < SYSDATE)
   AND (E.DTFIM IS NULL OR E.DTFIM > SYSDATE)
   AND V.NUMATRICULA = '929521';
