-- Selecionando estrutura de carreira 

SELECT C.CDESTRUTURACARREIRA,
       CA1.DEITEMCARREIRA,
       CA.DEITEMCARREIRA,
       C.CDESTRUTURACARREIRAPAI
  FROM ECADESTRUTURACARREIRA C
 INNER JOIN ECADITEMCARREIRA CA
    ON CA.CDITEMCARREIRA = C.CDITEMCARREIRA
 INNER JOIN ECADESTRUTURACARREIRA CP
    ON CP.CDESTRUTURACARREIRA = C.CDESTRUTURACARREIRAPAI
 INNER JOIN ECADITEMCARREIRA CA1
    ON CA1.CDITEMCARREIRA = CP.CDITEMCARREIRA
CONNECT BY PRIOR C.CDESTRUTURACARREIRAPAI = C.CDESTRUTURACARREIRA
 START WITH C.CDESTRUTURACARREIRA = 211;
