-- ===========================================================================
-- Tabela principal com os Documentos de Configuração Padrão no formato JSON
-- ===========================================================================
DROP TABLE emigConfiguracaoPadrao;

CREATE TABLE emigConfiguracaoPadrao (
  cdConfiguracaoPadrao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sgAgrupamento        VARCHAR2(15), 
  sgOrgao              VARCHAR2(15), 
  sgModulo             CHAR(3), 
  sgConceito           VARCHAR2(20), 
  dtExportacao         TIMESTAMP(6),
  cdIdentificacao      VARCHAR2(20), 
  jsConteudo           CLOB, 
  nuVersao             CHAR(04) DEFAULT '1.00', 
  flAnulado            CHAR(01) DEFAULT 'N', CHECK (flAnulado IN ('S','N')) ENABLE, 
  dtInclusao           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE emigConfiguracaoPadrao IS 'Armazena Documento JSON com as configuração contendo as parametrizações do agrupamento com estrutura hierárquica das tabelas envolvidas no conceito.';
COMMENT ON COLUMN emigConfiguracaoPadrao.cdConfiguracaoPadrao IS 'Identificador Único da Configuração Padrão.';
COMMENT ON COLUMN emigConfiguracaoPadrao.sgAgrupamento IS 'Sigla do Agrupamento de Órgãos.';
COMMENT ON COLUMN emigConfiguracaoPadrao.sgOrgao IS 'Sigla do Órgão quando houver Parametrização por Órgão (pode ser NULL).';
COMMENT ON COLUMN emigConfiguracaoPadrao.sgModulo IS 'Sigla do Módulo do SIGRH (ex: PAG, CAD, etc.).';
COMMENT ON COLUMN emigConfiguracaoPadrao.sgConceito IS 'Nome do Conceito de Parametrização (ex: RUBRICA, BASE, VALOR DE REFERENCIA).';
COMMENT ON COLUMN emigConfiguracaoPadrao.dtExportacao IS 'Data e hora do incio da operacao de exportação das configuraçõe';
COMMENT ON COLUMN emigConfiguracaoPadrao.cdIdentificacao IS 'Código Identificador da Entidade Parametrizada (ex: 01-0101).';
COMMENT ON COLUMN emigConfiguracaoPadrao.jsConteudo IS 'Documento JSON contendo os dados hierárquicos da parametrização.';
COMMENT ON COLUMN emigConfiguracaoPadrao.nuVersao IS 'Versão do Documento de Configuração Padrão (ex: 1.00).';
COMMENT ON COLUMN emigConfiguracaoPadrao.flAnulado IS 'Indicador lógico de anulação da entidade parametrizada (S/N).';
COMMENT ON COLUMN emigConfiguracaoPadrao.dtInclusao IS 'Data e hora da inclusão da parametrização.';

-- Busca rápida por agrupamento, órgão, módulo, conceito e código de identificação
CREATE INDEX idxemigConfiguracaoPadraoChave ON emigConfiguracaoPadrao (
  sgAgrupamento,
  sgOrgao,
  sgModulo,
  dtExportacao,
  sgConceito,
  cdIdentificacao
);
