-- ===========================================================================
-- Tabela de Log e Auditoria do Processamento das Exportação e Importação
-- dos Conceitos de Parametrização.
-- ===========================================================================
DROP TABLE emigConfiguracaoPadraoLog;

CREATE TABLE emigConfiguracaoPadraoLog (
  idlog                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sgAgrupamento        VARCHAR2(15),
  sgOrgao              VARCHAR2(15),
  sgModulo             CHAR(3),
  sgConceito           VARCHAR2(20),
  tpOperacao           VARCHAR2(15),
  dtOperacao           TIMESTAMP(6),
  nmEntidade           VARCHAR2(50),
  cdIdentificacao      VARCHAR2(70),
  nmEvento             VARCHAR2(50),
  nuRegistros          NUMBER,
  deMensagem           VARCHAR2(4000),
  dtInclusao           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE emigConfiguracaoPadraoLog IS 'Registra eventos, ações e mensagens durante a exportação ou importação das parametrizações padrão.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.idlog IS 'Identificador sequencial do log.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.sgAgrupamento IS 'Sigla do Agrupamento relacionado ao evento.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.sgOrgao IS 'Sigla do Órgão, se nulo se refere a todos os órgãos.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.sgModulo IS 'Sigla do Módulo que originou o evento .';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.sgConceito IS 'Conceito associado à parametrização.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.tpOperacao IS 'Se o evento é de EXPORTACAO ou de IMPORTACAO.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.dtOperacao IS 'Data e hora do incio da operacao relacionada a todos os evento da operação.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.nmEntidade IS 'Entidade dentro do Conceito associado à parametrização, grupo de informações do Conceito.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.cdIdentificacao IS 'Código Identificador da Entidade Parametrizada afetada pela operação.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.nmEvento IS 'Nome do evento (INCLUSAO, ATUALIZACAO, EXCLUSAO, RESUMO).';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.nuRegistros IS 'Quantidade de registros envolvidos no evento';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.deMensagem IS 'Mensagem detalhada sobre a operação registrada.';
COMMENT ON COLUMN emigConfiguracaoPadraoLog.dtInclusao IS 'Data e hora de inclusão do evento.';

-- Índice composto para consultas por agrupamento e identificação
CREATE INDEX idxemigConfiguracaoPadraoLogChave ON emigConfiguracaoPadraoLog (
  sgAgrupamento,
  sgOrgao,
  sgModulo,
  sgConceito,
  tpOperacao,
  dtOperacao,
  nmEntidade,
  cdIdentificacao
);
