-- Selecionando informações de pagamento de folha mensal de jan/2020

SELECT FP.NUANOMESREFERENCIA,
       TF.NMTIPOFOLHA,
       V.NUMATRICULA,
       LPAD(R.CDTIPORUBRICA, 2, '0') || '-' || LPAD(R.NURUBRICA, 4, '0'),
       H.VLPAGAMENTO
  FROM EPAGFOLHAPAGAMENTO FP
 INNER JOIN EPAGHISTORICORUBRICAVINCULO H
    ON H.CDFOLHAPAGAMENTO = FP.CDFOLHAPAGAMENTO
 INNER JOIN EPAGTIPOFOLHAPAGAMENTO TFP
    ON FP.CDTIPOFOLHAPAGAMENTO = TFP.CDTIPOFOLHAPAGAMENTO
 INNER JOIN ECADVINCULO V
    ON V.CDVINCULO = H.CDVINCULO
 INNER JOIN EPAGRUBRICAAGRUPAMENTO RA
    ON RA.CDRUBRICAAGRUPAMENTO = H.CDRUBRICAAGRUPAMENTO
 INNER JOIN EPAGRUBRICA R
    ON R.CDRUBRICA = RA.CDRUBRICA
 INNER JOIN EPAGTIPOFOLHA TF
    ON TF.CDTIPOFOLHA = TFP.CDTIPOFOLHA
 WHERE FP.NUANOMESREFERENCIA = 202003
   AND FP.CDTIPOCALCULO = 1
   AND TFP.CDTIPOFOLHA = 1
   AND FP.FLCALCULODEFINITIVO = 'S'
