WITH
RubricasTributacao AS (
SELECT js.tpTributacao, SUBSTR(js.nuRubrica,1,2) AS nuTipoRubrica, SUBSTR(js.nuRubrica,4,4) AS nuRubrica
FROM JSON_TABLE('
{"RubricasTributacao":[
{"tpTributacao": "INSS", "nuRubrica": "05-0003"},
{"tpTributacao": "INSS GRATIFICACAO NATALINA", "nuRubrica": "05-0011"},
{"tpTributacao": "IRRF", "nuRubrica": "05-0004"},
{"tpTributacao": "IRRF FERIAS", "nuRubrica": "05-0030"},
{"tpTributacao": "IRRF GRATIFICACAO NATALINA", "nuRubrica": "05-0049"},
{"tpTributacao": "IPER", "nuRubrica": "05-0182"},
{"tpTributacao": "IPER GRATIFICACAO NATALINA", "nuRubrica": "05-0227"},
{"tpTributacao": "IPER [RRA]", "nuRubrica": "05-1015"},
{"tpTributacao": "IPER GRATIFICACAO NATALINA [RRA]", "nuRubrica": "05-1016"},
{"tpTributacao": "ABATE TETO", "nuRubrica": "05-8002"},
{"tpTributacao": "ABATE TETO GRATIFICACAO NATALINA", "nuRubrica": "05-8003"},
{"tpTributacao": "CPSM", "nuRubrica": NULL},
{"tpTributacao": "CPSM GRATIFICACAO NATALINA", "nuRubrica": NULL},
{"tpTributacao": "PENSAO ALIMENTICIA ADIANTAMENTO GRATIFICACAO NATALINA", "nuRubrica": "05-1586"},
{"tpTributacao": "PENSAO ALIMENTICIA GRATIFICACAO NATALINA", "nuRubrica": "05-0586"},
{"tpTributacao": "PENSAO ALIMENTICIA [RRA]", "nuRubrica": null}
]}', '$.RubricasTributacao[*]' COLUMNS (
  tpTributacao PATH '$.tpTributacao',
  nuRubrica   PATH '$.nuRubrica'
)) js
),
ParametroTributacao AS (
SELECT cdRubricaAgrupamentoParametro, tpTributacao FROM JSON_TABLE('
{"ParametroTributacao":[
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescINSS", "tpTributacao": "INSS"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescINSSSobre13", "tpTributacao": "INSS GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescIRRF", "tpTributacao": "IRRF"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescIRRFSobre13", "tpTributacao": "IRRF GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescIRRFSobreFerias", "tpTributacao": "IRRF FERIAS"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIPrevFundFinanc", "tpTributacao": "IPER [RRA]"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIPrevFundFinanc13", "tpTributacao": "IPER GRATIFICACAO NATALINA [RRA]"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIPrevFundLC662", "tpTributacao": "IPER [RRA]"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIPrevFundLC66213", "tpTributacao": "IPER GRATIFICACAO NATALINA [RRA]"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIPrevFundPrev", "tpTributacao": "IPER [RRA]"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescIPrevAntes2008", "tpTributacao": "IPER"},
{"cdRubricaAgrupamentoParametro": "cdRubricaAgrupDescIPESC", "tpTributacao": "IPER"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIDescPescSobre13", "tpTributacao": "IPER GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubricaAgrupDescIPECJul2008", "tpTributacao": "IPER"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupIDescPescJul200813", "tpTributacao": "IPER GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubricaAgrupDescCPSM", "tpTributacao": "CPSM "},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupDescCPMSMSobre13", "tpTributacao": "CPSM GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupPensao13", "tpTributacao": "PENSAO ALIMENTICIA"},
{"cdRubricaAgrupamentoParametro": "cdRubricaAdiant13Pensao", "tpTributacao": "PENSAO ALIMENTICIA ADIANTAMENTO GRATIFICACAO NATALINA	"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupPensaoAliRRA", "tpTributacao": "PENSAO ALIMENTICIA [RRA]	"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupBloqRet", "tpTributacao": "ABATE TETO"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupBloqRet13Sal", "tpTributacao": "ABATE TETO"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupBloqRetExercFind", "tpTributacao": "ABATE TETO GRATIFICACAO NATALINA"},
{"cdRubricaAgrupamentoParametro": "cdRubAgrupBloqExercFind13Sal", "tpTributacao": "ABATE TETO GRATIFICACAO NATALINA"}
]}', '$.ParametroTributacao[*]' COLUMNS (
  cdRubricaAgrupamentoParametro PATH '$.cdRubricaAgrupamentoParametro',
  tpTributacao   PATH '$.tpTributacao'
)) js
),
AgrupamentoTributacao AS (
SELECT a.sgAgrupamento, JSON_OBJECT('RubricaAgrupamentoParametro' VALUE JSON_ARRAYAGG(
  JSON_OBJECT(parm.cdRubricaAgrupamentoParametro VALUE rubagrp.cdRubricaAgrupamento)
)) AS AgrupamentoTributacao
FROM ParametroTributacao parm
LEFT JOIN RubricasTributacao trib ON trib.tpTributacao = parm.tpTributacao
LEFT JOIN epagTipoRubrica tpRub ON tpRub.nuTipoRubrica = trib.nuTipoRubrica
LEFT JOIN epagRubrica rub ON rub.cdTipoRubrica = tpRub.cdTipoRubrica AND rub.nuRubrica = trib.nuRubrica
LEFT JOIN epagRubricaAgrupamento rubagrp ON rubagrp.cdRubrica = rub.cdRubrica
LEFT JOIN ecadAgrupamento a ON a.cdAgrupamento = rubagrp.cdAgrupamento
WHERE rubagrp.cdAgrupamento IS NOT NULL
GROUP BY a.sgAgrupamento
),
AgrupamentoParametro AS (
SELECT 
(SELECT MAX(NVL(cdagrupamentoparametro,0)) FROM epagAgrupamentoParametro) + ROWNUM AS cdagrupamentoparametro2,
agrpparm.cdagrupamentoparametro,
agrpparm.cdagrupamento,
agrpparm.nuanoiniciovigencia,
agrpparm.numesiniciovigencia,
agrpparm.nuanofimvigencia,
agrpparm.numesfimvigencia,
agrpparm.nuanoiniverifsalario,
agrpparm.numesiniverifsalario,
agrpparm.vlpagocconaopossuitpincorp,
agrpparm.vlpagoccopossuitpincorp,
agrpparm.vlpagoccocarreira,
agrpparm.flrecebeadiantamentos13,
agrpparm.vltetoauxilioalimvinc,
agrpparm.vlpercsobrebasefgts,
agrpparm.vlpercmultafgts,
agrpparm.cdtipotributacaoirrf,
agrpparm.nucpfcadastrador,
agrpparm.dtinclusao,
agrpparm.dtultalteracao,
agrpparm.vlpercentadiant13,
agrpparm.vlpercentadiant13descpensao,
agrpparm.flobrigaconsignacao,
agrpparm.flobrigarestituicao,
agrpparm.vlpercrestituicao,
agrpparm.vllimitepagretroativo,
agrpparm.nucnpjinss,
agrpparm.flprocretroativoobrigatorio,
agrpparm.cdrespodirf,
agrpparm.nudddrespodirf,
agrpparm.nutelefonerespodirf,
agrpparm.cdgrupodespesamedicadirf,
agrpparm.cdorgaoresponsavelrais,
agrpparm.cdresponsavelrais,
agrpparm.nudddresponsavelrais,
agrpparm.nutelefoneresponsavelrais,
agrpparm.qtmaxpessoas,
agrpparm.nuidadeapocompulsoria,
agrpparm.vllimitedirfsemvinculo,
agrpparm.vllimitedirfcomvinculo,
agrpparm.flpagarecisaofolhaespec,
agrpparm.vlpercrestituicaobolsista,
agrpparm.flbloqueianaorecadastrado,
agrpparm.cdmotivoafasttemporario,
agrpparm.fltributarraseparado,
agrpparm.fldescafastseparado,
agrpparm.flgerainssfolhaferias,
agrpparm.nuaproxirrfpensao,
agrpparm.flgerapensaofolhaferias,
agrpparm.nuhorainicialretera,
agrpparm.nuhorafinalretera,
agrpparm.cdrubagrupdescipescsobre13,
agrpparm.cdrubricaagrupdescipescjul2008,
agrpparm.cdrubagrupdescipescjul200813,
agrpparm.cdrubricaagrupdescrra,
agrpparm.cdrubagrupdescjudicial,
agrpparm.cdrubagrupdesciprevliminar,
agrpparm.cdrubagrupdesccpsmsobre13,
agrpparm.cdrubagrupdesccpsmretera,
agrpparm.cdrubagrupdesccpsmretera13,
agrpparm.cdrubricaagrupdesciprevjun2016,
agrpparm.cdrubricaagrupdesciprevjun1613,
agrpparm.cdrubagrupdesciprevdepois2008,

js.cdRubAgrupDescINSS,
js.cdRubAgrupDescINSSSobre13,
js.cdRubAgrupDescIRRF,
js.cdRubAgrupDescIRRFSobre13,
js.cdRubAgrupDescIRRFSobreFerias,
js.cdRubAgrupIPrevFundFinanc,
js.cdRubAgrupIPrevFundFinanc13,
js.cdRubAgrupIPrevFundLC662,
js.cdRubAgrupIPrevFundLC66213,
js.cdRubAgrupIPrevFundPrev,
js.cdRubAgrupDescIPrevAntes2008,
js.cdRubricaAgrupDescIPESC,
js.cdRubAgrupIDescPescSobre13,
js.cdRubricaAgrupDescIPECJul2008,
js.cdRubAgrupIDescPescJul200813,
js.cdRubricaAgrupDescCPSM,
js.cdRubAgrupDescCPMSMSobre13,
js.cdRubAgrupPensao13,
js.cdRubricaAdiant13Pensao,
js.cdRubAgrupPensaoAliRRA,
js.cdRubAgrupBloqRet,
js.cdRubAgrupBloqRet13Sal,
js.cdRubAgrupBloqRetExercFind,
js.cdRubAgrupBloqExercFind13Sal
FROM AgrupamentoTributacao trib
CROSS APPLY JSON_TABLE(trib.AgrupamentoTributacao, '$.RubricaAgrupamentoParametro' COLUMNS (
cdRubAgrupDescINSS            PATH '$.cdRubAgrupDescINSS',
cdRubAgrupDescINSSSobre13     PATH '$.cdRubAgrupDescINSSSobre13',
cdRubAgrupDescIRRF            PATH '$.cdRubAgrupDescIRRF',
cdRubAgrupDescIRRFSobre13     PATH '$.cdRubAgrupDescIRRFSobre13',
cdRubAgrupDescIRRFSobreFerias PATH '$.cdRubAgrupDescIRRFSobreFerias',
cdRubAgrupIPrevFundFinanc     PATH '$.cdRubAgrupIPrevFundFinanc',
cdRubAgrupIPrevFundFinanc13   PATH '$.cdRubAgrupIPrevFundFinanc13',
cdRubAgrupIPrevFundLC662      PATH '$.cdRubAgrupIPrevFundLC662',
cdRubAgrupIPrevFundLC66213    PATH '$.cdRubAgrupIPrevFundLC66213',
cdRubAgrupIPrevFundPrev       PATH '$.cdRubAgrupIPrevFundPrev',
cdRubAgrupDescIPrevAntes2008  PATH '$.cdRubAgrupDescIPrevAntes2008',
cdRubricaAgrupDescIPESC       PATH '$.cdRubricaAgrupDescIPESC',
cdRubAgrupIDescPescSobre13    PATH '$.cdRubAgrupIDescPescSobre13',
cdRubricaAgrupDescIPECJul2008 PATH '$.cdRubricaAgrupDescIPECJul2008',
cdRubAgrupIDescPescJul200813  PATH '$.cdRubAgrupIDescPescJul200813',
cdRubricaAgrupDescCPSM        PATH '$.cdRubricaAgrupDescCPSM',
cdRubAgrupDescCPMSMSobre13    PATH '$.cdRubAgrupDescCPMSMSobre13',
cdRubAgrupPensao13            PATH '$.cdRubAgrupPensao13',
cdRubricaAdiant13Pensao       PATH '$.cdRubricaAdiant13Pensao',
cdRubAgrupPensaoAliRRA        PATH '$.cdRubAgrupPensaoAliRRA',
cdRubAgrupBloqRet             PATH '$.cdRubAgrupBloqRet',
cdRubAgrupBloqRet13Sal        PATH '$.cdRubAgrupBloqRet13Sal',
cdRubAgrupBloqRetExercFind    PATH '$.cdRubAgrupBloqRetExercFind',
cdRubAgrupBloqExercFind13Sal  PATH '$.cdRubAgrupBloqExercFind13Sal'
)) js
LEFT JOIN ecadAgrupamento a ON a.sgAgrupamento = trib.sgAgrupamento
LEFT JOIN epagAgrupamentoParametro agrpparm ON agrpparm.cdAgrupamento = a.cdAgrupamento
WHERE a.sgAgrupamento = 'INDIR-IPEM/RR'
)

SELECT 
cdagrupamentoparametro,
cdagrupamento,
nuanoiniciovigencia,
numesiniciovigencia,
nuanofimvigencia,
numesfimvigencia,
nuanoiniverifsalario,
numesiniverifsalario,
vlpagocconaopossuitpincorp,
vlpagoccopossuitpincorp,
vlpagoccocarreira,
cdrubricaagrupdescipesc,
cdrubagrupdescipescsobre13,
cdrubagrupdescinss,
cdrubagrupdescinsssobre13,
cdrubagrupdescirrf,
cdrubagrupdescirrfsobre13,
cdrubagrupdescirrfsobreferias,
flrecebeadiantamentos13,
vltetoauxilioalimvinc,
vlpercsobrebasefgts,
vlpercmultafgts,
cdtipotributacaoirrf,
nucpfcadastrador,
dtinclusao,
dtultalteracao,
vlpercentadiant13,
vlpercentadiant13descpensao,
flobrigaconsignacao,
flobrigarestituicao,
vlpercrestituicao,
vllimitepagretroativo,
cdrubricaagrupdescipescjul2008,
cdrubagrupdescipescjul200813,
nucnpjinss,
flprocretroativoobrigatorio,
cdrubagrupiprevfundfinanc,
cdrubagrupiprevfundprev,
cdrubagrupbloqret,
cdrubagrupbloqretexercfind,
cdrubricaadiant13pensao,
cdrubagrupbloqret13sal,
cdrubagrupbloqexercfind13sal,
cdrespodirf,
nudddrespodirf,
nutelefonerespodirf,
cdgrupodespesamedicadirf,
cdorgaoresponsavelrais,
cdresponsavelrais,
nudddresponsavelrais,
nutelefoneresponsavelrais,
qtmaxpessoas,
nuidadeapocompulsoria,
cdrubagruppensao13,
vllimitedirfsemvinculo,
vllimitedirfcomvinculo,
flpagarecisaofolhaespec,
vlpercrestituicaobolsista,
flbloqueianaorecadastrado,
cdmotivoafasttemporario,
cdrubricaagrupdescrra,
fltributarraseparado,
cdrubagruppensaoalirra,
fldescafastseparado,
flgerainssfolhaferias,
nuaproxirrfpensao,
flgerapensaofolhaferias,
cdrubricaagrupdesciprevjun2016,
cdrubricaagrupdesciprevjun1613,
cdrubagrupdesciprevantes2008,
cdrubagrupdesciprevdepois2008,
cdrubagrupiprevfundlc662,
cdrubagrupiprevfundfinanc13,
cdrubagrupiprevfundlc66213,
cdrubricaagrupdesccpsm,
cdrubagrupdesccpsmsobre13,
cdrubagrupdesccpsmretera,
cdrubagrupdesccpsmretera13,
cdrubagrupdesciprevliminar,
nuhorainicialretera,
nuhorafinalretera,
cdrubagrupdescjudicial
FROM AgrupamentoParametro
;
/

